=== jonelo/xml-holidays/xml-holidays/src/xml/holidays.dtd
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
 -->
 
<!ENTITY % months "January | February | March | April |
                   May | June | July | August | September |
                   October | November | December">
<!ENTITY % weekdays "Monday | Tuesday | Wednesday | Thursday |
                     Friday | Saturday | Sunday">
<!ENTITY % nth "First | Second | Third | Fourth | Last">
<!ENTITY % startdate "fixed | easter | advent | rule | dst | equinox | solstice">
<!ENTITY % modifiers "add | goto">
<!ENTITY % directions "nearest | next | nextpossible | previous | previouspossible">

<!ELEMENT holidays (holiday+)>
<!ATTLIST holidays
          country CDATA #REQUIRED>

   <!--
     A holiday can have one import element or a combination of both definitions
     and code 
     "name"          is the localized name for the holiday, it must be set in
                     any case. Don't use english, except the local language
                     is english. Use the local description of the holiday
                     in your country.
     "international" is the english (international) well known name for the
                     holiday (optional). The local rules don't need to 
                     necessarily match with the well known english holiday.
     "valid"         determines whether the holiday is still valid or not
     "type"          currently free text, it can be anything, it further
                     describes the type of the holiday (e.g. legal holiday,
                     de facto legal holiday, katholic, etc.)
   -->
   <!ELEMENT holiday (import|(definition+|code+)+)>
   <!ATTLIST holiday
             name CDATA #REQUIRED
             type CDATA #IMPLIED
             valid (true|false) "true"
             international CDATA #IMPLIED>
      
      <!--
        An import element imports the definitions of a holiday from the
        file called holidays_shared.xml
      -->
      <!ELEMENT import EMPTY>
      <!ATTLIST import
                name CDATA #REQUIRED>

      <!-- The code element can keep Java code -->
      <!ELEMENT code (#PCDATA)>
      <!ATTLIST code
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED>

      <!--
        The definition is either
        * undefined or 
        * unkonwn or
        * it is a startdate, followed by a modifier or a condition
      -->
      <!ELEMENT definition (undefined | unknown | ((%startdate;),(%modifiers; | condition)*))>
      <!--
        year       the year when the holiday is valid,
                   same as if firstyear equals lastyear
                   the frequency, firstyear and lastyear are being ignored
                   if year is set
        firstyear  the first year when the holiday is valid (inclusively)
        lastyear   the last year when the holiday was valid (inclusively)
        frequency  how many years must pass, until the next year is valid?
                   (the actual start of the frequency depends on the firstyear
                   respectively on the lastyear if firstyear is not set)
        ifweekday  only valid if the date is on a particular weekday.
        ifdaytype  only valid if the type of the date is of a particular type.
        ifdayofmonth only valid if the day is a particular day of a month
      -->
      <!ATTLIST definition
                year CDATA #IMPLIED
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED
                frequency CDATA #IMPLIED>
      <!--
        a condition can be undefined, unknown or it can have multiple modifiers
      -->
      <!ELEMENT condition (undefined | unknown | (%modifiers;)*)>
      <!ATTLIST condition
                ifweekday (%weekdays;) #IMPLIED
                ifdaytype CDATA #IMPLIED
                ifdayname CDATA #IMPLIED
                ifdayofmonth CDATA #IMPLIED>
          
      <!--
        The undefined element says that a holiday wasn't/isn't
        defined during the years of the definition
      -->
      <!ELEMENT undefined EMPTY>
          
      <!--
        The empty element defines that we don't know the definition
      -->
      <!ELEMENT unknown EMPTY>

      <!--
        The fixed element defines a fixed date
      -->
      <!ELEMENT fixed EMPTY>
      <!ATTLIST fixed 
	        month (%months;) #REQUIRED
	        day CDATA #REQUIRED>

      <!--
        The Daylight Saving Time (dst) definition
        action defines whether the DST starts or whether the DST ends
      -->
      <!ELEMENT dst EMPTY>
      <!ATTLIST dst
                timezone CDATA #REQUIRED
                action (start|end) #IMPLIED>

      <!--
        This is the startdate of Easter
        Western churches use the Gregorian Calendar to calculate the date
        of Easter and Eastern Orthodox churches use the Julian Calendar
      -->
      <!ELEMENT easter EMPTY>
      <!ATTLIST easter
                church (western|eastern) "western">

      <!--
        This is the startdate of the 1st advent
      -->
      <!ELEMENT advent EMPTY>

      <!--
        http://en.wikipedia.org/wiki/Equinox
        "March equinox" and "September equinox"
        Names avoid the classical Northern Hemisphere bias implied by the
        assumption that March is in springtime and September is in autumn;
        only true for those in the Northern Hemisphere but actually the
        complete opposite for dwellers in the Southern Hemisphere.
      -->          
      <!ELEMENT equinox EMPTY>
      <!ATTLIST equinox
                month (March|September) #REQUIRED
                timezone CDATA #REQUIRED>
          
      <!--
        http://en.wikipedia.org/wiki/Solstice
      -->
      <!ELEMENT solstice EMPTY>
      <!ATTLIST solstice
                month (June|December) #REQUIRED
                timezone CDATA #REQUIRED>
        
      <!--
        The rule defines the nth weekday of a month
      -->
      <!ELEMENT rule EMPTY>
      <!ATTLIST rule
                nth (%nth;) #REQUIRED
                weekday (%weekdays;) #REQUIRED
                month (%months;) #REQUIRED>
      <!--
        The add modifier
        the "add" property value can become positive or negative
      -->
      <!ELEMENT add EMPTY>
      <!ATTLIST add
                days CDATA #REQUIRED>
        
      <!--
        The goto modifier
        moves to the next, previous or nearest weekday
        the direction can become
        nearest - the nearest weekday, go not more than 3 days in one direction
        next - the next weekday
        nextpossible - a "goto next" action happens only if the current
                       weekday is not the specified weekday
        previous - the previous weekday
        previouspossible - a "goto previous" action happens only if the current
                           weekday is not the specified weekday
      -->
      <!ELEMENT goto EMPTY>
      <!ATTLIST goto
                weekday (%weekdays;) #REQUIRED
                direction (%directions;) "nearest">

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_jp.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="jp">
    <!-- http://en.wikipedia.org/wiki/Holidays_of_Japan 
         http://www.japan-guide.com/e/e2062.html -->

    <holiday name="Ganjitsu" type="national holiday">
        <import name="New Year's Day"/>
    </holiday>
    
    <holiday name="Seijin no hi" type="national holiday"
             international="Coming of Age">
        <!-- This national holiday was established in 1948 -->
        <definition firstyear="1948" lastyear="1999">
            <fixed day="15" month="January"/>
        </definition>
        <!-- Originally held on January 15, in 2000 it was changed to
             the second Monday of January -->
        <definition firstyear="2000">
            <rule nth="2nd" weekday="Monday" month="January"/>
        </definition>
    </holiday>

    <holiday name="setsubun)">
        <definition>
            <fixed day="3" month="February"/>
        </definition>
    </holiday>
    
    <holiday name="Kigen-setsu" valid="false">
        <!-- From 1872 to 1948, February 11 was known as Kigen-setsu -->
        <definition firstyear="1872" lastyear="1948"/>
            <fixed day="11" month="February"/>
        </definition>
    </holiday>
    
    <holiday name="Kenkoku kinen no hi" type="national holiday">
        <!-- This national holiday was established in 1966
             (and first held in 1967) -->
        <definition firstyear="1967">
            <fixed day="11" month="February"/>
        </definition>
    </holiday>
    
    <holiday name="Valentine's Day">
        <import name="Valentine's Day"/>
    </holiday>
    
    <holiday name="hina matsuri" type="national holiday"
             international="Doll's Festival">
        <definition>
            <fixed day="3" month="March"/>
        </definition>
    </holiday>

    <!-- http://www.japan-guide.com/topic/0003.html -->
    <holiday name="hina matsuri" type="national holiday"
             international="White Day">
        <definition>
            <fixed day="14" month="March"/>
        </definition>
    </holiday>


    <!-- Prior to 1948, the vernal equinox was an imperial
         ancestor worship festival called Shunki kōrei-sai -->
<!--    <holiday name="Shunki kōrei-sai">
        <definition lastyear="1947">
             <equinox type="vernal"/>
        </definition>
    </holiday>
-->

    <!-- This national holiday was established in 1948 -->
    <!-- Around March 20 -->
<!--    <holiday name="Shunbun no hi" type="national holiday"
             international="Vernal equinox">
         <definition firstyear="1948">
             <equinox type="vernal"/>
         </definition>
    </holiday>
-->

    <!-- http://en.wikipedia.org/wiki/Sh%C5%8Dwa_Day -->
    <holiday name="Shōwa no hi" type="national holiday"
             international="Shōwa Day">
        <definition firstyear="2007">
            <fixed day="29" month="April"/>
        </definition>
    </holiday>
    
    <!-- http://en.wikipedia.org/wiki/Constitution_Memorial_Day -->
    <holiday name="Kenpō kinenbi" type="national holiday"
             international="Constitution Memorial Day">
        <!-- This national holiday was established in 1948 -->
        <definition firstyear="1948">
            <fixed day="3" month="May"/>
        </definition>
    </holiday>

    <!-- From 1986 to 2006, May 4 was a holiday known as Kokumin no kyūjitsu -->
    <holiday name="Kokumin no kyūjitsu" valid="false">
        <definition firstyear="1986" lastyear="2006"/>
             <fixed day="4" month="May"/>
        </definition>
    </holiday>
    
    <holiday name="Midori no hi" type="national holiday"
             international="Greenery Day">
        <!-- Until 2006, Greenery Day was celebrated on April 29 -->
        <definition lastyear="2006">
             <fixed day="29" month="April"/>
         </definition>
        <!-- in 2007, Greenery Day was moved to May 4 -->
        <definition firstyear="2007">
            <fixed day="4" month="May"/>
        </definition>
    </holiday>

    <holiday name="Kodomo no hi" type="national holiday"
             international="Children's Day">
         <!-- This national holiday was established in 1948 -->
         <definition>
              <fixed day="5" month="May"/>
         </definition>
    </holiday>
    
    <holiday name="Umi no hi" type="national holiday"
             international="Marine Day">
          <!-- This national holiday was established in 1995
               (and first held in 1996) -->
          <defintion firstyear="1996" lastyear="2002">
              <fixed day="20" month="July"/>
          </defintion>
          <!-- Originally held on July 20, in 2003 it was changed to
               the third Monday of July -->
          <definition firstyear="2003">
              <rule nth="3rd" weekday="Monday" month="July"/>
          </definition>
    </holiday>
    

    
    
    <holiday name="Begin Daylight Saving Time (DST)">
        <definition>
            <dst timezone="Asia/Tokyo" action="start"/>
        </definition>
    </holiday>
    
    <holiday name="End Daylight Saving Time (DST)">
        <definition>
            <dst timezone="Asia/Tokyo" action="end"/>
        </definition>
    </holiday>
    
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_li.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="li">
    <!-- Lichtenstein http://www.tourismus.li/de/navpage-RegionLI-InformationLI-44728.html-->

    <holiday name="Neujahrstag" type="gesetzlich" international="New Year's Day">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    <holiday name="Berchtoldstag (Bankfeiertag)">
        <definition>
            <fixed month="January" day="2"/>
        </definition>
    </holiday>
    <holiday name="Hl. Drei Könige" type="gesetzlich" international="Epiphany">
        <definition>
            <fixed month="January" day="6"/>
        </definition>
    </holiday>
    <holiday name="Mariä Lichtmess">
        <definition>
            <fixed month="February" day="2"/>
        </definition>
    </holiday>
    <holiday name="Fastnachtsdienstag (Bankfeiertag)">
        <import name="Carnival"/>
    </holiday>
    <holiday name="Beginn der Sommerzeit (Uhren 1 h vorstellen)" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Vaduz" action="start"/>
        </definition>
    </holiday>
    <holiday name="Karfreitag (Bankfeiertag)" type="gesetzlich" international="Good Friday">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    <holiday name="Ostersonntag (Ostern)" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>
    <holiday name="Ostermontag (Emmaustag)" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>
    <holiday name="Tag der Arbeit" type="gesetzlich">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>
    <holiday name="Auffahrt" type="gesetzlich">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>
    <holiday name="Pfingstsonntag (Pfingsten)" type="gesetzlich" international="Whit Sunday">
        <import name="Pentecost"/>
    </holiday>
    <holiday name="Pfingstmontag" type="gesetzlich">
        <definition>
            <easter/>
            <add days="+50"/>
        </definition>
    </holiday>
    <holiday name="Fronleichnam" type="gesetzlich" international="Corpus Christi">
        <definition>
            <easter/>
            <add days="+60"/>
        </definition>
    </holiday>
    <holiday name="Staatsfeiertag" type="gesetzlich">
        <definition>
            <fixed month="August" day="15"/>
        </definition>
    </holiday>
    <holiday name="Maria Geburt" type="gesetzlich">
        <definition>
            <fixed month="September" day="8"/>
        </definition>
    </holiday>
    <holiday name="Ende der Sommerzeit (Uhren 1 h zurückstellen)" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Vaduz" action="end"/>
        </definition>
    </holiday>
    <holiday name="Allerheiligen" type="gesetzlich" international="All Saints">
        <!-- All Saint's Day is a Christian holy day observed by many Western churches on November 1 -->
        <import name="All Saints’ Day"/>
    </holiday>
    <holiday name="Nikolaus" international="Saint Nicholas Day">
        <definition>
            <fixed month="December" day="6"/>
        </definition>
    </holiday>
    <holiday name="Mariä Empfängnis" type="gesetzlich">
        <definition>
            <fixed month="December" day="8"/>
        </definition>
    </holiday>
    <holiday name="Heiligabend (Bankfeiertage)" international="Christmas Eve">
        <import name="Christmas Eve"/>
    </holiday>
    <holiday name="Weihnachten" type="gesetzlich" international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    <holiday name="2. Weihnachtsfeiertag/Stephanstag" type="gesetzlich" international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
    <holiday name="Silvester (Bankfeiertage)" international="New Year's Eve">
        <import name="New Year's Eve"/>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_ar.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="ar">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Argentina -->

    <!--
     TODO:
     The following are federal non-working religious holidays
     (people of the relevant faiths are excused from work):
     Jewish New Year (Judaism)
     Day of Atonement (Judaism)
     End of Ramadan (Islam)
     Muslim New Year (Islam)
    -->

    <holiday name="Año Nuevo" type="public holiday">
        <import name="New Year's Day"/>
    </holiday>

    <holiday name="Eastern Orthodox Christmas Day"
             type="federal non-working religious holiday (people of the relevant faiths are excused from work)">
        <definition>
            <fixed day="7" month="January"/>
        </definition>
    </holiday> 
    
    <holiday name="Jueves Santo" type="public holiday">
        <import name="Maundy Thursday"/>
    </holiday>
    
    <holiday name="Viernes Santo" type="public holiday">
        <import name="Good Friday"/>
    </holiday>
    
    <!-- http://en.wikipedia.org/wiki/Day_of_Memory_for_Truth_and_Justice -->
    <holiday name="Día de la Memoria por la Verdad y la Justicia"
             type="public holiday"
             international="Day of Memory for Truth and Justice">
        <definition firstyear="1976">
            <fixed day="24" month="March"/>
        </definition>
    </holiday>

    <!-- http://en.wikipedia.org/wiki/Malvinas_Day -->
    <holiday name="Día de los caídos en Malvinas"
             type="public holiday"
             international="Malvinas Day">
        <definition firstyear="1982">
            <fixed day="2" month="April"/>
        </definition>
    </holiday>

    <!-- http://en.wikipedia.org/wiki/Malvinas_Day -->
    <holiday name="Día del Trabajador" type="public holiday"
             international="Labor Day">
        <definition>
            <fixed day="1" month="May"/>
        </definition>
    </holiday>

    <!-- http://en.wikipedia.org/wiki/May_Revolution -->
    <holiday name="Revolución de Mayo" type="public holiday"
             international="May Revolution">
        <definition firstyear="1810">
            <fixed day="25" month="May"/>
        </definition>
    </holiday>
    
    <holiday name="Día de la Bandera" international="National Flag Day"
             type="public holiday">
        <definition>
            <rule nth="3rd" weekday="Monday" month="June"/>
        </definition>
    </holiday>
    
    <holiday name="Father's Day">
        <definition>
            <rule nth="3rd" weekday="Sunday" month="June"/>
        </definition>
    </holiday>
    
    <holiday name="New Year's Day for indigenous cultures" type="federal non-working religious holiday (people of the relevant faiths are excused from work)">
        <definition>
            <fixed day="21" month="June"/>
        </definition>
    </holiday>


    <!-- http://en.wikipedia.org/wiki/May_Revolution -->
    <holiday name="Día de la Independencia" type="public holiday"
             international="National Independence Day">
        <definition firstyear="1810">
            <fixed day="9" month="July"/>
        </definition>
    </holiday>
    
    <holiday name="Día del Libertador José de San Martín"
        international="Anniversary of the death of General José de San Martín"
        type="public holiday">
        <definition>
            <rule nth="3rd" weekday="Monday" month="August"/>
        </definition>
    </holiday>
    
    <holiday name="Children's Day">
        <definition>
            <rule nth="2nd" weekday="Sunday" month="August"/>
        </definition>
    </holiday>
    
    <!-- http://en.wikipedia.org/wiki/Columbus_Day -->
    <holiday name="Día de la Raza" international="Columbus Day"
             type="public holiday">
        <definition firstyear="1917">
            <fixed day="12" month="October"/>
            <!--
              If the date falls on a Tuesday or Wednesday,
              the holiday is the preceding Monday.
            -->
            <add days="-1" ifweekday="Tuesday"/> <!-- can become the preceding Monday -->
            <add days="-2" ifweekday="Wednesday"/> <!-- can become the preceding Monday -->
            <!--
              If it falls on a Thursday or a Friday then
              the holiday is the following Monday.
            -->
            <add days="+4" ifweekday="Thursday"/> <!-- can become the following Monday -->
            <add days="+3" ifweekday="Friday"/> <!-- can become the following Monday -->
        </definition>
    </holiday>
    
    <holiday name="Día del Maestro" international="Teacher's Day" type="only observed by primary school students">
        <definition>
            <fixed day="11" month="September"/>
        </definition>
    </holiday>
    
    <!-- http://en.wikipedia.org/wiki/Mother%27s_Day -->
    <holiday name="Mother's Day">
        <definition>
            <rule nth="3rd" weekday="Sunday" month="October"/>
        </definition>
    </holiday>
    
    <holiday name="Día del Estudiante/Día de la Primavera" international="Student's Day/Spring Day" type="only observed by high-school students">
        <definition>
            <fixed day="21" month="November"/>
        </definition>
    </holiday>   

    <holiday name="Día de la Inmaculada Concepción" type="public holiday">
        <definition>
            <fixed day="8" month="December"/>
        </definition>
    </holiday>
    
    <holiday name="Nochebuena" type="public holiday">
        <import name="Christmas Eve"/>
    </holiday>
    
    <holiday name="Día de Navidad" type="public holiday">
        <import name="Christmas Day"/>
    </holiday>

    <holiday name="Fin de Año" type="public holiday">
        <import name="Christmas Day"/>
    </holiday>
   
    <holiday name="Begin Daylight Saving Time (DST)">
        <definition>
            <dst timezone="America/Buenos_Aires" action="start"/>
        </definition>
    </holiday>
    
    <holiday name="End Daylight Saving Time (DST)">
        <definition>
            <dst timezone="America/Buenos_Aires" action="end"/>
        </definition>
    </holiday>
    
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_gr.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="gr">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Greece -->

    <holiday name="Πρωτοχρονιά / Protochronia" type="public holiday">
        <import name="New Year's Day"/>
    </holiday>
    
    <holiday name="Θεοφάνεια / Theofania" type="public holiday"
             international="Epiphany">
        <definition>
            <fixed month="January" day="6"/>
        </definition>
    </holiday>
    
    <holiday name="Τριών Ιεραρχών / Trion Ierarchon" type="school holiday only"
             international="The Three Holy Hierarchs">
        <definition>
            <fixed month="January" day="30"/>
        </definition>
    </holiday>
    
    <holiday name="Καθαρή Δευτέρα / Kathari Devtera" type="public holiday"
             international="Ash Monday (eastern churches)">
        <definition>
            <easter church="eastern"/>
            <add days="-48"/>
        </definition>
    </holiday>
    
    <holiday name="Ευαγγελισμός Θεοτόκου / Eikosti-pempti Martiou" type ="public holiday"
             international="25th of March">
        <definition>
            <fixed month="March" day="25"/>
        </definition>
    </holiday>
    
    <holiday name="Begin Daylight Saving Time" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Athens" action="start"/>
        </definition>
    </holiday>
    
    <holiday name="Κυριακή του Πάσχα / Kyriaki tou Pascha"
             international="Easter Sunday (eastern churches)">
        <definition>
            <easter church="eastern"/>
        </definition>
    </holiday>
    
    <holiday name="Δευτέρα του Πάσχα / Deutera tou Pascha" type="public holiday"
             international="Easter Monday (eastern churches)">
        <definition>
            <easter church="eastern"/>
            <add days="+1"/>
        </definition>
    </holiday>
    
    <holiday name="Εργατική Πρωτομαγιά / Ergatiki Protomagia" type="public holiday"
             international="Labour Day">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>
    
    <holiday name="Πνευματος / Pnevmatos" type="public holiday"
             international="Pentecost (eastern churches)">
        <definition>
            <easter church="eastern"/>
            <add days="+49"/>
        </definition>
    </holiday>
    
    <holiday name="Αγιου Πνευματος / Tou Agiou Pnevmatos" type="public holiday"
             international="Pentecost Monday (eastern churches)">
        <definition>
            <easter church="eastern"/>
            <add days="+50"/>
        </definition>
    </holiday>
    
    <holiday name="Η Κοίμησις της Θεοτόκου / Panaghias" type="public holiday"
             international="The Dormition of the Holy Virgin">
        <definition>
            <fixed month="August" day="15"/>
        </definition>
    </holiday>
    
    <holiday name="End Daylight Saving Time"
             international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Athens" action="end"/>
        </definition>
    </holiday>
    
    <!-- http://en.wikipedia.org/wiki/Oxi_Day -->
    <holiday name="Το Όχι / To Ochi" type="public holiday"
             international="The Ochi day">
        <definition firstyear="1942">
            <fixed month="October" day="28"/>
        </definition>
    </holiday>
    
    <holiday name="Πολυτεχνείο / Polytechneio" type="school holiday only"
             international="Polytechneio">
        <definition firstyear="1973">
            <fixed month="November" day="17"/>
        </definition>
    </holiday>
    
    <holiday name="Χριστούγεννα / Christougenna" type="public holiday"
             international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    
    <holiday name="Σύναξις Θεοτόκου / Synaxis Theotokou" type="public holiday"
             international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
</holidays>
