=== jonelo/xml-holidays/xml-holidays/src/xml/holidays.dtd
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
 -->
 
<!ENTITY % months "January | February | March | April |
                   May | June | July | August | September |
                   October | November | December">
<!ENTITY % weekdays "Monday | Tuesday | Wednesday | Thursday |
                     Friday | Saturday | Sunday">
<!ENTITY % nth "First | Second | Third | Fourth | Last">
<!ENTITY % startdate "fixed | easter | advent | rule | dst | equinox | solstice">
<!ENTITY % modifiers "add | goto">
<!ENTITY % directions "nearest | next | nextpossible | previous | previouspossible">

<!ELEMENT holidays (holiday+)>
<!ATTLIST holidays
          country CDATA #REQUIRED>

   <!--
     A holiday can have one import element or a combination of both definitions
     and code 
     "name"          is the localized name for the holiday, it must be set in
                     any case. Don't use english, except the local language
                     is english. Use the local description of the holiday
                     in your country.
     "international" is the english (international) well known name for the
                     holiday (optional). The local rules don't need to 
                     necessarily match with the well known english holiday.
     "valid"         determines whether the holiday is still valid or not
     "type"          currently free text, it can be anything, it further
                     describes the type of the holiday (e.g. legal holiday,
                     de facto legal holiday, katholic, etc.)
   -->
   <!ELEMENT holiday (import|(definition+|code+)+)>
   <!ATTLIST holiday
             name CDATA #REQUIRED
             type CDATA #IMPLIED
             valid (true|false) "true"
             international CDATA #IMPLIED>
      
      <!--
        An import element imports the definitions of a holiday from the
        file called holidays_shared.xml
      -->
      <!ELEMENT import EMPTY>
      <!ATTLIST import
                name CDATA #REQUIRED>

      <!-- The code element can keep Java code -->
      <!ELEMENT code (#PCDATA)>
      <!ATTLIST code
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED>

      <!--
        The definition is either
        * undefined or 
        * unkonwn or
        * it is a startdate, followed by a modifier or a condition
      -->
      <!ELEMENT definition (undefined | unknown | ((%startdate;),(%modifiers; | condition)*))>
      <!--
        year       the year when the holiday is valid,
                   same as if firstyear equals lastyear
                   the frequency, firstyear and lastyear are being ignored
                   if year is set
        firstyear  the first year when the holiday is valid (inclusively)
        lastyear   the last year when the holiday was valid (inclusively)
        frequency  how many years must pass, until the next year is valid?
                   (the actual start of the frequency depends on the firstyear
                   respectively on the lastyear if firstyear is not set)
        ifweekday  only valid if the date is on a particular weekday.
        ifdaytype  only valid if the type of the date is of a particular type.
        ifdayofmonth only valid if the day is a particular day of a month
      -->
      <!ATTLIST definition
                year CDATA #IMPLIED
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED
                frequency CDATA #IMPLIED>
      <!--
        a condition can be undefined, unknown or it can have multiple modifiers
      -->
      <!ELEMENT condition (undefined | unknown | (%modifiers;)*)>
      <!ATTLIST condition
                ifweekday (%weekdays;) #IMPLIED
                ifdaytype CDATA #IMPLIED
                ifdayname CDATA #IMPLIED
                ifdayofmonth CDATA #IMPLIED>
          
      <!--
        The undefined element says that a holiday wasn't/isn't
        defined during the years of the definition
      -->
      <!ELEMENT undefined EMPTY>
          
      <!--
        The empty element defines that we don't know the definition
      -->
      <!ELEMENT unknown EMPTY>

      <!--
        The fixed element defines a fixed date
      -->
      <!ELEMENT fixed EMPTY>
      <!ATTLIST fixed 
	        month (%months;) #REQUIRED
	        day CDATA #REQUIRED>

      <!--
        The Daylight Saving Time (dst) definition
        action defines whether the DST starts or whether the DST ends
      -->
      <!ELEMENT dst EMPTY>
      <!ATTLIST dst
                timezone CDATA #REQUIRED
                action (start|end) #IMPLIED>

      <!--
        This is the startdate of Easter
        Western churches use the Gregorian Calendar to calculate the date
        of Easter and Eastern Orthodox churches use the Julian Calendar
      -->
      <!ELEMENT easter EMPTY>
      <!ATTLIST easter
                church (western|eastern) "western">

      <!--
        This is the startdate of the 1st advent
      -->
      <!ELEMENT advent EMPTY>

      <!--
        http://en.wikipedia.org/wiki/Equinox
        "March equinox" and "September equinox"
        Names avoid the classical Northern Hemisphere bias implied by the
        assumption that March is in springtime and September is in autumn;
        only true for those in the Northern Hemisphere but actually the
        complete opposite for dwellers in the Southern Hemisphere.
      -->          
      <!ELEMENT equinox EMPTY>
      <!ATTLIST equinox
                month (March|September) #REQUIRED
                timezone CDATA #REQUIRED>
          
      <!--
        http://en.wikipedia.org/wiki/Solstice
      -->
      <!ELEMENT solstice EMPTY>
      <!ATTLIST solstice
                month (June|December) #REQUIRED
                timezone CDATA #REQUIRED>
        
      <!--
        The rule defines the nth weekday of a month
      -->
      <!ELEMENT rule EMPTY>
      <!ATTLIST rule
                nth (%nth;) #REQUIRED
                weekday (%weekdays;) #REQUIRED
                month (%months;) #REQUIRED>
      <!--
        The add modifier
        the "add" property value can become positive or negative
      -->
      <!ELEMENT add EMPTY>
      <!ATTLIST add
                days CDATA #REQUIRED>
        
      <!--
        The goto modifier
        moves to the next, previous or nearest weekday
        the direction can become
        nearest - the nearest weekday, go not more than 3 days in one direction
        next - the next weekday
        nextpossible - a "goto next" action happens only if the current
                       weekday is not the specified weekday
        previous - the previous weekday
        previouspossible - a "goto previous" action happens only if the current
                           weekday is not the specified weekday
      -->
      <!ELEMENT goto EMPTY>
      <!ATTLIST goto
                weekday (%weekdays;) #REQUIRED
                direction (%directions;) "nearest">

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_fr.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="fr">
    <!-- Frankreich http://www.feiertagskalender.ch -->

    <holiday name="Le Jour de l'An" type="gesetzlich" international="New Year's Day">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>

    <holiday name="Valentinstag">
        <import name="Valentine's Day"/>
    </holiday>

    <holiday name="Beginn der Sommerzeit (Uhren 1 h vorstellen)" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Paris" action="start"/>
        </definition>
    </holiday>

    <holiday name="Palmsonntag (Palmarum)" international="Palm Sunday">
        <definition>
            <easter/>
            <add days="-7"/>
        </definition>
    </holiday>

    <holiday name="Karfreitag" type="katholisch" international="Good Friday">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>

    <holiday name="Pâques" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>

    <holiday name="Le lundi de Le lundi de Pâques" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>

    <holiday name="La fête du Travail" type="gesetzlich" international="Labour Day">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>

    <holiday name="L'Ascension" type="gesetzlich" international="Ascension Day">
        <definition>
            <easter/>
            <add days="+39"/>
        </definition>
    </holiday>

    <holiday name="Fête de la Victoire 1945" type="gesetzlich" international="WWII Victory Day">
        <definition firstyear="1945">
            <fixed month="May" day="8"/>
        </definition>
    </holiday>

    <holiday name="Pfingstsonntag (Pfingsten)" type="katholisch">
        <import name="Pentecost"/>
    </holiday>

    <holiday name="Muttertag">
        <!-- 2. Sonntag im Mai -->
        <definition>
            <rule nth="2nd" weekday="Sunday" month="May"/>
        </definition>
    </holiday>

    <holiday name="La fête nationale" type="gesetzlich" international="Bastille Day">
        <definition>
            <fixed month="July" day="14"/>
        </definition>
    </holiday>

    <holiday name="L'Assomption" type="gesetzlich" international="Assumption of Mary">
        <definition>
            <fixed month="August" day="15"/>
        </definition>
    </holiday>

    <holiday name="Ende der Sommerzeit (Uhren 1 h zurückstellen)" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Paris" action="end"/>
        </definition>
    </holiday>

    <holiday name="La Toussaint" type="gesetzlich" international="All Saints’ Day">
        <!-- All Saint's Day is a Christian holy day observed by many Western churches on November 1 -->
        <import name="All Saints’ Day"/>
    </holiday>

    <holiday name="L'Armistice" type="gesetzlich" international="Armistice Day">
        <definition firstyear="1918">
            <fixed month="November" day="11"/>
        </definition>
    </holiday>

    <holiday name="St. Nikolaus" type="katholisch">
        <definition>
            <fixed month="December" day="6"/>
        </definition>
    </holiday>

    <holiday name="1. Advent" type="katholisch">
        <import name="1st Advent"/>
    </holiday>

    <holiday name="2. Advent" type="katholisch">
        <import name="2nd Advent"/>
    </holiday>

    <holiday name="3. Advent (Gaudete)" type="katholisch">
        <import name="3rd Advent"/>
    </holiday>

    <holiday name="4. Advent" type="katholisch">
        <import name="4th Advent"/>
    </holiday>

    <holiday name="Noël" type="gesetzlich">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>

    <holiday name="2. Noël" type="katholisch">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>

    <holiday name="Silvester" type="katholisch">
        <import name="New Year's Eve"/>
    </holiday>
    
    <holiday name="Équinoxe mars">
        <definition>
            <equinox type="March" timezone="Europe/Paris"/>
        </definition>
    </holiday>
    
    <holiday name="Solstice juin">
        <definition>
            <equinox type="June" timezone="Europe/Paris"/>
        </definition>
    </holiday>
    
    <holiday name="Équinoxe sept">
        <definition>
            <equinox type="September" timezone="Europe/Paris"/>
        </definition>
    </holiday>
    
    <holiday name="Solstice déc">
        <definition>
            <equinox type="December" timezone="Europe/Paris"/>
        </definition>
    </holiday> 
    
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_nl.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="nl">
    <!-- Niederlande http://mobile.feiertagskalender.ch/index.php?geo=3192&jahr=2007&klasse=5&hl=de -->

    <holiday name="Neujahrstag" type="gesetzlich" international="New Year's Day">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    <holiday name="Beginn der Sommerzeit (Uhren 1 h vorstellen)" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Amsterdam" action="start"/>
        </definition>
    </holiday>
    <holiday name="Karfreitag" type="gesetzlich" international="Good Friday">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    <holiday name="Ostern" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>
    <holiday name="Ostermontag (Emmaustag)" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>
    <holiday name="Koninginnedag (Nationalfeiertag)">
    	<!-- Wenn Sonntag dann wird Samstag gefeiert -->
        <definition>
            <fixed month="April" day="30"/>
            <add days="-1" ifweekday="Sunday"/>
        </definition>
    </holiday>
    <holiday name="Tag der Befreiung">
        <definition>
            <fixed month="May" day="5"/>
        </definition>
    </holiday>
    <holiday name="Muttertag">
        <!-- 2. Sonntag im Mai -->
        <definition>
            <rule nth="2nd" weekday="Sunday" month="May"/>
        </definition>
    </holiday>
    <holiday name="Christi Himmelfahrt" type="gesetzlich">
        <definition>
            <easter/>
            <add days="+39"/>
        </definition>
    </holiday>
    <holiday name="Pfingstsonntag (Pfingsten)" type="gesetzlich" international="Whit Sunday">
        <import name="Pentecost"/>
    </holiday>
    <holiday name="Pfingstmontag" type="gesetzlich" international="Whit Monday">
        <definition>
            <easter/>
            <add days="+50"/>
        </definition>
    </holiday>
    <holiday name="Ende der Sommerzeit (Uhren 1 h zurÃ¼ckstellen)" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Amsterdam" action="end"/>
        </definition>
    </holiday>
    <holiday name="1. Weihnachtsfeiertag (Weihnachten)" type="gesetzlich" international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    <holiday name="2. Weihnachtsfeiertag" type="gesetzlich" international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_sk.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="SK">
    <!-- Slowak. Republik http://feiertagskalender.ch/index.php?geo=3453&jahr=2008&klasse=5&hl=de&hidepast=0-->

    <holiday name="Deň vzniku Slovenskej republiky" type="gesetzlich">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    <holiday name="Zjavenie Pána" type="gesetzlich" international="Epiphany">
        <definition>
            <fixed month="January" day="6"/>
        </definition>
    </holiday>
    <holiday name="Valentinstag">
        <import name="Valentine's Day"/>
    </holiday>
    <holiday name="Beginn der Sommerzeit (Uhren 1 h vorstellen)" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Bratislava" action="start"/>
        </definition>
    </holiday>
    <holiday name="Veľký piatok" type="gesetzlich" international="Good Friday">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    <holiday name="Veľkonočná nedeľa" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>
    <holiday name="Veľkonočný pondelok" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>
    <holiday name="Sviatok práce" type="gesetzlich" international="Labor Day">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>
    <holiday name="Výročie úmrtia M. R. ŝtefánika (Anniversary of the Decease of M. R. ŝtefánika)">
        <definition>
            <fixed month="May" day="4"/>
        </definition>
    </holiday>
    <holiday name="Deň víťazstva nad faŝizmom (End of World War II)" type="gesetzlich">
        <definition>
            <fixed month="May" day="8"/>
        </definition>
    </holiday>
    <holiday name="Muttertag">
        <!-- 2. Sonntag im Mai -->
        <definition>
            <rule nth="Second" weekday="Sunday" month="May"/>
        </definition>
    </holiday>
    <holiday name="Sviatok svätého Cyrila a Metoda (St. Cyril and St. Methodius Day)" type="gesetzlich">
        <definition>
            <fixed month="July" day="5"/>
        </definition>
    </holiday>
    <holiday name="Výročie SNP (National Uprising Day)" type="gesetzlich">
        <definition>
            <fixed month="August" day="29"/>
        </definition>
    </holiday>
    <holiday name="Deň Ústavy Slovenskej republiky (Constitution Day)" type="gesetzlich">
        <definition>
            <fixed month="September" day="1"/>
        </definition>
    </holiday>
    <holiday name="Deň obetí holokaustu a rasového násilia (Day of the Victims of Holocaust and of racial violence)">
        <definition>
            <fixed month="September" day="9"/>
        </definition>
    </holiday>
    <holiday name="Sedembolestná Panna Mária (The Day of the Virgin Mary of the Seven Sorrows)" type="gesetzlich">
        <definition>
            <fixed month="September" day="15"/>
        </definition>
    </holiday>
    <holiday name="Deň vzniku Slovenskej národnej rady (Day of the First Public Appearance of the Slovak National Council)">
        <definition>
            <fixed month="September" day="19"/>
        </definition>
    </holiday>
    <holiday name="Deň obetí Dukly (Dukla Pass Victims Day)">
        <definition>
            <fixed month="October" day="6"/>
        </definition>
    </holiday>
    <holiday name="Ende der Sommerzeit (Uhren 1 h zurückstellen)" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Bratislava" action="end"/>
        </definition>
    </holiday>
    <holiday name="Deň černovskej tragédie (Černová Tragedy Day)">
        <definition>
            <fixed month="October" day="27"/>
        </definition>
    </holiday>
    <holiday name="Deň vzniku samostatného Česko-slovenského Ŝtátu (Day of the Establishment of an Independent Czecho-Slovak State)">
        <definition>
            <fixed month="October" day="28"/>
        </definition>
    </holiday>
    <holiday name="Deň narodenia Ľ. Ŝtúra (Birth of Ľudovít Ŝtúr Day)">
        <definition>
            <fixed month="October" day="29"/>
        </definition>
    </holiday>
    <holiday name="Výročie Deklarácie slovenského národa (Anniversary of the Declaration of the Slovak Nation)">
        <definition>
            <fixed month="October" day="30"/>
        </definition>
    </holiday>
    <holiday name="Deň reformácie (Reformation Day)">
        <definition>
            <fixed month="October" day="31"/>
        </definition>
    </holiday>
    <holiday name="Sviatok vŝetkých svätých" type="gesetzlich" international="All Saints">
        <!-- All Saint's Day is a Christian holy day observed by many Western churches on November 1 -->
        <import name="All Saints’ Day"/>
    </holiday>
    <holiday name="Deň boja za slobodu a demokraciu (Day of the Fight for Freedom and Democracy)" type="gesetzlich">
        <definition>
            <fixed month="November" day="17"/>
        </definition>
    </holiday>
    <holiday name="Ŝtedrý deň" type="gesetzlich" international="Christmas Eve">
        <import name="Christmas Eve"/>
    </holiday>
    <holiday name="Prvý sviatok vianočný" type="gesetzlich" international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    <holiday name="Druhý sviatok vianočný" type="gesetzlich" international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
    <holiday name="Deň vyhlásenia Slovenska za samostatnú cirkevnú (Day of the Declaration of Slovakia as an Independent Ecclesiastic Province)">
        <definition>
            <fixed month="December" day="30"/>
        </definition>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_at.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="at">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Austria.html#Austria -->

    <holiday name="Neujahrstag" type="gesetzlich">
        <import name="New Year's Day"/>
    </holiday>

    <holiday name="Hl. Drei Könige" international="Three Kings Day">
        <definition>
            <fixed month="January" day="6"/>
        </definition>
    </holiday>

    <holiday name="Josef" type="local [Kärnten, Steiermark, Tirol, Vorlarlberg]">
        <definition>
            <fixed month="March" day="19"/>
        </definition>
    </holiday>

    <holiday name="Beginn der Sommerzeit (Uhren 1 h vorstellen)" international="Start Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Vienna" action="start" />
        </definition>
    </holiday>

    <holiday name="Karfreitag">
        <import name="Good Friday"/>
    </holiday>

    <holiday name="Ostersonntag (Ostern)">
        <import name="Easter Sunday"/>
    </holiday>

    <holiday name="Ostermontag">
        <import name="Easter Monday"/>
    </holiday>

    <holiday name="Staatsfeiertag (Tag der Arbeit)" international="Labour Day">
        <definition>
            <fixed day="1" month="May" />
        </definition>
    </holiday>

    <holiday name="Florian" type="local [Oberösterreich]">
        <definition>
            <fixed day="4" month="May" />	
        </definition>
    </holiday>

    <holiday name="Christi Himmelfahrt">
        <import name="Ascension of Jesus"/>
    </holiday>

    <holiday name="Pfingstsonntag (Pfingsten)">
        <import name="Pentecost"/>
    </holiday>

    <holiday name="Pfingstmontag">
        <import name="Whit Monday"/>
    </holiday>

    <holiday name="Fronleichnam">
        <import name="Corpus Christi"/>
    </holiday>

    <holiday name="Mariä Himmelfahrt">
        <definition>
            <fixed day="15" month="August" />	
        </definition>
    </holiday>

    <holiday name="Rupert" type="local [Salzburg]">
        <definition>
            <fixed day="24" month="September" />	
        </definition>
    </holiday>

    <holiday name="Tag der Volksabstimmung" type="local [Kärnten]">
        <definition firstyear="1920">
            <fixed day="10" month="October" />	
        </definition>
    </holiday>

    <holiday name="Nationalfeiertag">
        <definition firstyear="1965">
            <fixed day="26" month="October" />	
        </definition>
    </holiday>

    <holiday name="Ende der Sommerzeit (Uhren 1 h zurückstellen)" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Vienna" action="end" />	
        </definition>
    </holiday>

    <holiday name="Weltspartag (gefeiert)">
        <import name="Weltspartag (gefeiert)"/>
    </holiday>

    <holiday name="Weltspartag (offiziell)">
        <import name="Weltspartag (offiziell)"/>
    </holiday>

    <holiday name="Allerheiligen">
        <import name="All Saints' Day"/>
    </holiday>

    <holiday name="Martin" type="local [Burgenland]">
        <definition>
            <fixed day="11" month="November"/>		
        </definition>
    </holiday>

    <holiday name="Leopold" type="local [Niederösterreich, Wien]">
        <definition>
            <fixed day="15" month="November"/>	
        </definition>
    </holiday>

    <holiday name="Mariä Empfängnis" international="Immaculate Conception">
        <definition>
            <fixed day="8" month="December"/>		
        </definition>
    </holiday>

    <holiday name="Heiliger Abend">
        <definition>
            <fixed day="24" month="December"/>		
        </definition>
    </holiday>

    <holiday name="Christtag">
        <import name="Christmas Day"/>
    </holiday>

    <holiday name="Stefanitag">
        <definition>
            <fixed day="26" month="December"/>	
        </definition>
    </holiday>

    <holiday name="Silvester">
        <import name="New Year's Eve"/>
    </holiday>

    <holiday name="Frühlingsanfang" international="Equinox March">
        <definition>
            <equinox month="March" timezone="Europe/Vienna"/>
        </definition>
    </holiday>
    
    <holiday name="Sommeranfang (Sommersonnenwende)" international="Solstice June">
        <definition>
            <solstice month="June" timezone="Europe/Vienna"/>
        </definition>
    </holiday>
    
    <holiday name="Herbstanfang" international="Equinox September">
        <definition>
            <equinox month="September" timezone="Europe/Vienna"/>
        </definition>
    </holiday>

    <holiday name="Winteranfang (Wintersonnenwende)" international="Solstice December">
        <definition>
            <solstice month="December" timezone="Europe/Vienna"/>
        </definition>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_int.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="int">
    <!-- See also http://en.wikipedia.org/wiki/Category:United_Nations_days -->

    <!--
      http://en.wikipedia.org/wiki/Earth_Day
      -->
    <holiday name="Earth Day">
        <definition firstyear="1970">
            <fixed month="April" day="22"/>
        </definition>
    </holiday>
    
    <!-- 
      http://www.sueddeutsche.de/kultur/artikel/690/115575/
      0x25+0x5=37+5=42 ;)
      -->
    <holiday name="Towel Day">
        <definition lastyear="2000">
            <undefined/>
        </definition>
        <definition firstyear="2001">
            <fixed month="May" day="25"/>
        </definition>
    </holiday>
    
    <!--
       http://en.wikipedia.org/wiki/World_AIDS_Day
    -->
    <holiday name="World AIDS Day">
         <definition firstyear="1988">
             <fixed month="December" day="1"/>
         </definition>
    </holiday>

</holidays>
