=== jonelo/xml-holidays/xml-holidays/src/xml/holidays.dtd
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
 -->
 
<!ENTITY % months "January | February | March | April |
                   May | June | July | August | September |
                   October | November | December">
<!ENTITY % weekdays "Monday | Tuesday | Wednesday | Thursday |
                     Friday | Saturday | Sunday">
<!ENTITY % nth "First | Second | Third | Fourth | Last">
<!ENTITY % startdate "fixed | easter | advent | rule | dst | equinox | solstice">
<!ENTITY % modifiers "add | goto">
<!ENTITY % directions "nearest | next | nextpossible | previous | previouspossible">

<!ELEMENT holidays (holiday+)>
<!ATTLIST holidays
          country CDATA #REQUIRED>

   <!--
     A holiday can have one import element or a combination of both definitions
     and code 
     "name"          is the localized name for the holiday, it must be set in
                     any case. Don't use english, except the local language
                     is english. Use the local description of the holiday
                     in your country.
     "international" is the english (international) well known name for the
                     holiday (optional). The local rules don't need to 
                     necessarily match with the well known english holiday.
     "valid"         determines whether the holiday is still valid or not
     "type"          currently free text, it can be anything, it further
                     describes the type of the holiday (e.g. legal holiday,
                     de facto legal holiday, katholic, etc.)
   -->
   <!ELEMENT holiday (import|(definition+|code+)+)>
   <!ATTLIST holiday
             name CDATA #REQUIRED
             type CDATA #IMPLIED
             valid (true|false) "true"
             international CDATA #IMPLIED>
      
      <!--
        An import element imports the definitions of a holiday from the
        file called holidays_shared.xml
      -->
      <!ELEMENT import EMPTY>
      <!ATTLIST import
                name CDATA #REQUIRED>

      <!-- The code element can keep Java code -->
      <!ELEMENT code (#PCDATA)>
      <!ATTLIST code
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED>

      <!--
        The definition is either
        * undefined or 
        * unkonwn or
        * it is a startdate, followed by a modifier or a condition
      -->
      <!ELEMENT definition (undefined | unknown | ((%startdate;),(%modifiers; | condition)*))>
      <!--
        year       the year when the holiday is valid,
                   same as if firstyear equals lastyear
                   the frequency, firstyear and lastyear are being ignored
                   if year is set
        firstyear  the first year when the holiday is valid (inclusively)
        lastyear   the last year when the holiday was valid (inclusively)
        frequency  how many years must pass, until the next year is valid?
                   (the actual start of the frequency depends on the firstyear
                   respectively on the lastyear if firstyear is not set)
        ifweekday  only valid if the date is on a particular weekday.
        ifdaytype  only valid if the type of the date is of a particular type.
        ifdayofmonth only valid if the day is a particular day of a month
      -->
      <!ATTLIST definition
                year CDATA #IMPLIED
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED
                frequency CDATA #IMPLIED>
      <!--
        a condition can be undefined, unknown or it can have multiple modifiers
      -->
      <!ELEMENT condition (undefined | unknown | (%modifiers;)*)>
      <!ATTLIST condition
                ifweekday (%weekdays;) #IMPLIED
                ifdaytype CDATA #IMPLIED
                ifdayname CDATA #IMPLIED
                ifdayofmonth CDATA #IMPLIED>
          
      <!--
        The undefined element says that a holiday wasn't/isn't
        defined during the years of the definition
      -->
      <!ELEMENT undefined EMPTY>
          
      <!--
        The empty element defines that we don't know the definition
      -->
      <!ELEMENT unknown EMPTY>

      <!--
        The fixed element defines a fixed date
      -->
      <!ELEMENT fixed EMPTY>
      <!ATTLIST fixed 
	        month (%months;) #REQUIRED
	        day CDATA #REQUIRED>

      <!--
        The Daylight Saving Time (dst) definition
        action defines whether the DST starts or whether the DST ends
      -->
      <!ELEMENT dst EMPTY>
      <!ATTLIST dst
                timezone CDATA #REQUIRED
                action (start|end) #IMPLIED>

      <!--
        This is the startdate of Easter
        Western churches use the Gregorian Calendar to calculate the date
        of Easter and Eastern Orthodox churches use the Julian Calendar
      -->
      <!ELEMENT easter EMPTY>
      <!ATTLIST easter
                church (western|eastern) "western">

      <!--
        This is the startdate of the 1st advent
      -->
      <!ELEMENT advent EMPTY>

      <!--
        http://en.wikipedia.org/wiki/Equinox
        "March equinox" and "September equinox"
        Names avoid the classical Northern Hemisphere bias implied by the
        assumption that March is in springtime and September is in autumn;
        only true for those in the Northern Hemisphere but actually the
        complete opposite for dwellers in the Southern Hemisphere.
      -->          
      <!ELEMENT equinox EMPTY>
      <!ATTLIST equinox
                month (March|September) #REQUIRED
                timezone CDATA #REQUIRED>
          
      <!--
        http://en.wikipedia.org/wiki/Solstice
      -->
      <!ELEMENT solstice EMPTY>
      <!ATTLIST solstice
                month (June|December) #REQUIRED
                timezone CDATA #REQUIRED>
        
      <!--
        The rule defines the nth weekday of a month
      -->
      <!ELEMENT rule EMPTY>
      <!ATTLIST rule
                nth (%nth;) #REQUIRED
                weekday (%weekdays;) #REQUIRED
                month (%months;) #REQUIRED>
      <!--
        The add modifier
        the "add" property value can become positive or negative
      -->
      <!ELEMENT add EMPTY>
      <!ATTLIST add
                days CDATA #REQUIRED>
        
      <!--
        The goto modifier
        moves to the next, previous or nearest weekday
        the direction can become
        nearest - the nearest weekday, go not more than 3 days in one direction
        next - the next weekday
        nextpossible - a "goto next" action happens only if the current
                       weekday is not the specified weekday
        previous - the previous weekday
        previouspossible - a "goto previous" action happens only if the current
                           weekday is not the specified weekday
      -->
      <!ELEMENT goto EMPTY>
      <!ATTLIST goto
                weekday (%weekdays;) #REQUIRED
                direction (%directions;) "nearest">

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_no.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="NO">
    <!-- Norwegen http://www.ferienwohnungen-kroatien.net/feiertage/feiertage_norwegen.shtml -->

    <holiday name="Første nyttårsdag" type="gesetzlich" international="New Year's Day">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    <holiday name="Prinsesse Ingrid Alexandra">
        <definition>
            <fixed month="January" day="21"/>
        </definition>
    </holiday>
    <holiday name="Beginn der Sommerzeit (Uhren 1 h vorstellen)" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Oslo" action="start"/>
        </definition>
    </holiday>
    <holiday name="palmesøndag" international="Palm Sunday">
        <definition>
            <easter/>
            <add days="-7"/>
        </definition>
    </holiday>
    <holiday name="Skjærtorsdag" international="Maundy Thursday">
        <definition>
            <easter/>
            <add days="-3"/>
        </definition>
    </holiday>
    <holiday name="Langfredag" type="gesetzlich" international="Good Friday">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    <holiday name="1. påskedag" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>
    <holiday name="2. påskedag" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>
    <holiday name="Offentlig høytidsdag" type="gesetzlich">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>
    <holiday name="Kristi Himmelfartsdag" type="gesetzlich">
        <definition>
            <easter/>
            <add days="+39"/>
        </definition>
    </holiday>
    <holiday name="Frigjøringsdag 1945 (Day of liberation)">
        <definition>
            <fixed month="May" day="8"/>
        </definition>
    </holiday>
    <holiday name="Grunnlovsdag (Norges nasjonaldag)" type="gesetzlich">
        <definition firstyear="1814">
        	<fixed month="May" day="17" />
        </definition>
    </holiday>
    <holiday name="1. pinsedag" type="gesetzlich" international="Whit Sunday">
        <import name="Pentecost"/>
    </holiday>
    <holiday name="2. pinsedag" type="gesetzlich" international="Whit Monday">
        <definition>
            <easter/>
            <add days="+50"/>
        </definition>
    </holiday>
    <holiday name="Corpus Christi" international="Corpus Christi">
        <definition>
            <easter/>
            <add days="+60"/>
        </definition>
    </holiday>
    <holiday name="Unionsoppløsningen (End of union)">
        <definition firstyear="1905">
        	<fixed month="June" day="7" />
        </definition>
    </holiday>
    <holiday name="Dronning Sonja (Queen Sonja's day)">
        <definition>
        	<fixed month="July" day="4" />
        </definition>
    </holiday>
    <holiday name="Kronprins Haakon Magnus (Crown Prince Haakon Magnus' day)">
        <definition>
        	<fixed month="July" day="20" />
        </definition>
    </holiday>
    <holiday name="Ende der Sommerzeit (Uhren 1 h zurückstellen)" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Oslo" action="end"/>
        </definition>
    </holiday>
    <holiday name="Julaften" international="Christmas Eve">
        <import name="Christmas Eve"/>
    </holiday>
    <holiday name="1. Juledag" type="gesetzlich" international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    <holiday name="2. Juledag" type="gesetzlich" international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
    <holiday name="Nyttårsaften" international="New Year's Eve">
        <import name="New Year's Eve"/>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_ddr.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="ddr">
    <!-- DDR -->

    <holiday name="Neujahrstag" type="gesetzlich" international="New Year's Day">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    <holiday name="Karfreitag" type="gesetzlich" international="Good Friday">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    <holiday name="Ostersonntag (Ostern)" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>
    <holiday name="Ostermontag (Emmaustag)" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>
    <holiday name="Internationaler Kampf- und Feiertag der Werktätigen" type="gesetzlich">
        <definition firstyear="1950" lastyear="1990">
        	<fixed month="May" day="1" />
        </definition>
    </holiday>
    <holiday name="Tag der Befreiung" type="gesetzlich">
        <definition firstyear="1950" lastyear="1966">
        	<fixed month="May" day="8" />
        </definition>
    </holiday>
    <holiday name="Tag des Sieges" type="gesetzlich">
        <definition year="1975">
        	<fixed month="May" day="9" />
        </definition>
    </holiday>
    <holiday name="Christi Himmelfahrt" type="gesetzlich">
        <definition>
            <easter/>
            <add days="+39"/>
        </definition>
    </holiday>
    <holiday name="Pfingstsonntag (Pfingsten)" type="gesetzlich" international="Whit Sunday">
        <import name="Pentecost"/>
    </holiday>
    <holiday name="Pfingstmontag" type="gesetzlich">
        <definition>
            <easter/>
            <add days="+50"/>
        </definition>
    </holiday>
    <holiday name="Tag der Republik" type="gesetzlich">
        <definition firstyear="1949" lastyear="1989">
        	<fixed month="October" day="7" />
        </definition>
    </holiday>
    <holiday name="Reformationstag" type="gesetzlich">
        <definition>
            <fixed month="October" day="31"/>
        </definition>
    </holiday>
    <holiday name="Buß- und Bettag" type="gesetzlich">
        <definition>
            <advent/>
            <add days="-11"/>
        </definition>
    </holiday>
    <holiday name="1. Weihnachtsfeiertag (Weihnachten)" type="gesetzlich" international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    <holiday name="2. Weihnachtsfeiertag" type="gesetzlich" international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_ro.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="RO">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Romania -->

    <holiday name="Anul nou" type="Official non-working holiday" international="New Year's Day">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>

    <holiday name="2. Anul nou" type="Official non-working holiday" international="Day after New Year's Day">
        <definition>
            <fixed month="January" day="2"/>
        </definition>
    </holiday>

    <holiday name="Ziua Unirii" type="Official holiday" international="Unification Day">
        <definition>
            <fixed month="January" day="24"/>
        </definition>
    </holiday>
    
    <holiday name="Dragobetele" type="Traditional festival" international="St. Valentine's Day">
        <definition>
            <fixed month="February" day="24"/>
        </definition>
    </holiday>

    <holiday name="Mărţişorul" type="Traditional festival" international="Spring festival">
        <definition>
            <fixed month="March" day="1"/>
        </definition>
    </holiday>

    <holiday name="Ziua Unirii" type="Official holiday" international="Women's Day">
        <definition>
            <fixed month="March" day="8"/>
        </definition>
    </holiday>

    <holiday name="Paştele" type="Official non-working holiday" international="Easter">
        <definition>
            <easter church="eastern"/>
        </definition>
    </holiday>

    <holiday name="NATO Day" international="NATO Day" type="Not a public holiday">
        <definition>
            <rule nth="First" weekday="Sunday" month="April"/>
        </definition>
    </holiday>

    <holiday name="Ziua Eroilor (Înălţarea)" type="Official non-working holiday" international="Heroes' Day (Ascension)">
        <definition>
            <easter church="eastern"/>
            <!-- 40 days after the Orthodox Easter. -->
            <add days="40"/>
        </definition>
    </holiday>

    <holiday name="1. Rusaliile" type="Official non-working holiday" international="Pentecost, Whit Monday">
        <definition>
            <easter church="eastern"/>
            <!-- 50 days after the Orthodox Easter. -->
            <add days="50"/>
        </definition>
    </holiday>

    <holiday name="2. Rusaliile" type="Official non-working holiday" international="Whit Monday">
        <definition>
            <easter church="eastern"/>
            <!-- 51 days after the Orthodox Easter. -->
            <add days="51"/>
        </definition>
    </holiday>

    <holiday name="DST start" international="Begin Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Bucharest" action="start"/>
        </definition>
    </holiday>

    <holiday name="Ziua muncii" type="Official non-working holiday"
             international="Labour Day">
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>

    <holiday name="Ziua Copilului" international="Child's day"
             type="Official holiday">
        <definition>
            <fixed month="June" day="1"/>
        </definition>
    </holiday>
    
    <holiday name="Ziua Tricolorului" international="Flag Day"
             type="Official holiday">
        <!-- was first performed, in 1848 at Râmnicu Vâlcea -->
        <definition firstyear="1848">
            <fixed month="June" day="26"/>
        </definition>
    </holiday>    

    <holiday name="Ziua Imnului naţional" international="National Anthem Day"
             type="Official holiday">
        <definition>
            <fixed month="July" day="29"/>
        </definition>
    </holiday>

    <holiday name="Adormirea Maicii Domnului" type="Official non-working holiday"
             international="Dormition of the Theotokos">
        <definition>
            <fixed month="August" day="15"/>
        </definition>
    </holiday>

    <holiday name="Armed Forces Day" type="Not a public holiday"
             international="Armed Forces Day">
        <definition>
            <fixed month="October" day="25"/>
        </definition>
    </holiday>

    <holiday name="Ziua Naţională (Ziua Marii Uniri)" type="Official non-working holiday"
             international="National holiday (Great Union Day)">
        <definition>
            <fixed month="December" day="1"/>
        </definition>
    </holiday>

    <holiday name="Ziua Constituţiei" international="Constitution Day">
        <definition>
            <fixed month="December" day="8"/>
        </definition>
    </holiday>

    <holiday name="Crăciunul" type="Official non-working holiday"
             international="Christmas Day">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>

    <holiday name="A doua zi de Crăciun" type="Official non-working holiday"
             international="Boxing Day">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>

    <holiday name="DST end" international="End Daylight Saving Time">
        <definition>
            <dst timezone="Europe/Bucharest" action="end"/>
        </definition>
    </holiday>

</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_au.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">

<holidays country="AU">
    <!-- Australia -->

    <holiday name="New Year's Day(1.1.1901 - GrÃ¼ndungstag)" type="gesetzlich">
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    <holiday name="Australia Day(26.1.1788)" type="gesetzlich">
        <definition firstyear="1788">
        	<fixed month="January" day="26" />
        </definition>
    </holiday>
    <holiday name="Labour Day (Western Australia only)" type="local">
        <definition>
            <rule nth="First" weekday="Monday" month="March"/>
        </definition>
    </holiday>
    <holiday name="Eight Hours Day (Tasmania only)" type="local">
        <definition>
            <rule nth="Second" weekday="Monday" month="March"/>
        </definition>
    </holiday>
    <holiday name="Labour Day (Victoria only)" type="local">
        <definition>
            <rule nth="Second" weekday="Monday" month="March"/>
        </definition>
    </holiday>
    <holiday name="Good Friday" type="gesetzlich">
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    <holiday name="Easter Saturday" international="Holy Saturday">
        <definition>
            <easter/>
            <add days="-1"/>
        </definition>
    </holiday>
    <holiday name="Easter Sunday" type="gesetzlich">
        <import name="Easter Sunday"/>
    </holiday>
    <holiday name="Easter Monday" type="gesetzlich">
        <import name="Easter Monday"/>
    </holiday>
    <holiday name="ANZAC Day(1915)" type="gesetzlich">
        <definition>
            <fixed month="April" day="25"/>
        </definition>
    </holiday>
    <holiday name="May Day (Northern Territory only)" type="local">
        <definition>
            <rule nth="First" weekday="Monday" month="May"/>
        </definition>
    </holiday>
    <holiday name="Labour Day (Queensland only)" type="local">
        <definition>
            <rule nth="First" weekday="Monday" month="May"/>
        </definition>
    </holiday>
    <holiday name="Foundation Day(Western Australia only)" type="local">
        <definition>
            <rule nth="First" weekday="Monday" month="June"/>
        </definition>
    </holiday>
    <holiday name="Queen's Birthday(all exept WA)" type="local">
        <definition>
            <rule nth="Second" weekday="Monday" month="June"/>
        </definition>
    </holiday>
    <holiday name="Queen's Birthday(West Australia only)" type="local">
        <definition>
            <rule nth="First" weekday="Monday" month="October"/>
        </definition>
    </holiday>
    <holiday name="Labour Day(SA, ACT, NSW)" type="local">
        <definition>
            <rule nth="First" weekday="Monday" month="October"/>
        </definition>
    </holiday>
    <holiday name="Melbourne Cup Day(Victoria only)" type="local">
        <definition>
            <rule nth="First" weekday="Tuesday" month="November"/>
        </definition>
    </holiday>
    <holiday name="Christmas Day" type="gesetzlich">
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    <holiday name="Boxing Day" type="gesetzlich">
        <definition>
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
</holidays>

=== jonelo/xml-holidays/xml-holidays/src/xml/holidays_pa.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="pa">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Panama -->
    
    <holiday name="New Year's Day">
        <import name="New Year's Day"/>
    </holiday>
    
    <!-- http://en.wikipedia.org/wiki/Martyrs%27_Day_(Panama) -->
    <holiday name="Martyrs' Day">
        <definition firstyear="1964">
            <fixed day="9" month="January"/>
        </definition>
    </holiday>
    
    <holiday name="Carnival's Monday">
        <!-- The Monday before Ash Wednesday -->
        <definition>
            <easter/>
            <add days="-48"/>
        </definition>
    </holiday>
    
    <holiday name="Carnival's Tuesday">
        <!-- The Tuesday before Ash Wednesday -->
        <import name="Carnival"/>
    </holiday>
    
    <holiday name="Holy Friday">
        <!-- Friday of Roman Catholic Holy Week - Death of Christ -->
        <import name="Good Friday"/>
    </holiday>
    
    <holiday name="May Day" international="Labour Day">
        <definition>
            <fixed day="1" month="May"/>
        </definition>
    </holiday>
    
    <holiday name="Separation Day (from Colombia)">
        <definition>
            <fixed day="3" month="November"/>
        </definition>
    </holiday>
    
    <holiday name="Flag Day">
        <definition>
            <fixed day="4" month="November"/>
        </definition>
    </holiday>
    
    <holiday name="Colon Day">
        <definition>
            <fixed day="5" month="November"/>
        </definition>
    </holiday>
    
    <holiday name="Primer Grito de Independencia de la Villa de los Santos"
             international="The uprise in the Villa de los Santos against Spain.">
        <definition>
            <fixed day="10" month="November"/>
        </definition>
    </holiday>
    
    <holiday name="Independence Day (from Spain)">
        <definition>
            <fixed day="28" month="November"/>
        </definition>
    </holiday>
    
    <holiday name="Mothers' Day">
        <definition>
            <fixed day="8" month="December"/>
        </definition>
    </holiday>
    
    <holiday name="Christmas">
        <import name="Christmas Day"/>
    </holiday> 
    
    <holiday name="Begin Daylight Saving Time (DST)">
        <definition>
            <dst timezone="America/Panama" action="start"/>
        </definition>
    </holiday>
    
    <holiday name="End Daylight Saving Time (DST)">
        <definition>
            <dst timezone="America/Panama" action="end"/>
        </definition>
    </holiday>
    
</holidays>
