=== jonelo/xml-holidays/xml/holidays.dtd
<!-- 
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
 -->
 
<!ENTITY % months "January | February | March | April |
                   May | June | July | August | September |
                   October | November | December">
<!ENTITY % weekdays "Monday | Tuesday | Wednesday | Thursday |
                     Friday | Saturday | Sunday">
<!ENTITY % nth "First | Second | Third | Fourth | Last">
<!ENTITY % startdate "fixed | easter | advent | rule | dst |
                      equinox | solstice | lunisolar">
<!ENTITY % modifiers "add | goto">
<!ENTITY % directions "nearest | next | nextinclusive | previous | previousinclusive">

<!--
  The element called holidays must have at least one element called holiday
  "country"         the ID of the country
                    use ISO 3166-1-alpha-2 code in uppercase characters
                    if applicable
  -->
<!ELEMENT holidays (default+,holiday+)>
<!ATTLIST holidays
          country CDATA #REQUIRED>

   <!--
     The default element specifies a language which is common in a country
     "language"      specify the language for a holiday name.
                     Use ISO 639-1-alpha-2 code in lowercase characters
                     if applicable.
    -->
   <!ELEMENT default EMPTY>
   <!ATTLIST default
             language CDATA #REQUIRED>
   <!--
     A holiday can have one import element or a combination of both definitions
     and code
     "id"            an optional identification (holiday is usually identified
                     by the holiday name)
     "valid"         indicates whether the holiday is still valid or not
                     (use false if it is a history or obsolete holiday)
   -->
   <!ELEMENT holiday (description+,(import|definition+))>
   <!ATTLIST holiday
             id CDATA #IMPLIED
             valid (true|false) "true">

      <!-- 
        "language"   the language in which the name of the holiday is expressed
        "name"       the name of the holiday expressed in "language"
        "type"       free text, it should further describe the type of the
                     holiday (e.g. legal holiday, de facto legal holiday,
                     katholic, etc.)
        "region"     free text, the region of the holiday if applicable
        -->
      <!ELEMENT description EMPTY>
      <!ATTLIST description
                language CDATA #REQUIRED
                name CDATA #REQUIRED
                type CDATA #IMPLIED
                region CDATA #IMPLIED>

      <!--
        An import element imports the definitions of a holiday from the
        file called holidays_shared.xml
      -->
      <!ELEMENT import EMPTY>
      <!ATTLIST import
                id CDATA #REQUIRED>

      <!--
        The definition is either
        * undefined or 
        * unkonwn or
        * it is a startdate, followed by a modifier or a condition
      -->
      <!ELEMENT definition (undefined | unknown | ((%startdate;),(%modifiers; | condition)*))>
      <!--
        year       the year when the holiday is valid,
                   same as if firstyear equals lastyear
                   the frequency, firstyear and lastyear are being ignored
                   if year is set
        firstyear  the first year when the holiday is valid (inclusively)
        lastyear   the last year when the holiday was valid (inclusively)
        frequency  how many years must pass, until the next year is valid?
                   (the actual start of the frequency depends on the firstyear
                   respectively on the lastyear if firstyear is not set)
        ifweekday  only valid if the date is on a particular weekday.
        ifdaytype  only valid if the type of the date is of a particular type.
        ifdayofmonth only valid if the day is a particular day of a month
      -->
      <!ATTLIST definition
                year CDATA #IMPLIED
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED
                frequency CDATA #IMPLIED>
      <!--
        a condition can be undefined, unknown or it can have multiple modifiers
      -->
      <!ELEMENT condition (undefined | unknown | (%modifiers;)*)>
      <!ATTLIST condition
                ifweekday (%weekdays;) #IMPLIED
                ifdaytype CDATA #IMPLIED
                ifdayname CDATA #IMPLIED
                ifdayofmonth CDATA #IMPLIED
                language CDATA #IMPLIED>
          
      <!--
        The undefined element says that a holiday wasn't/isn't
        defined during the years of the definition
      -->
      <!ELEMENT undefined EMPTY>
          
      <!--
        The empty element defines that we don't know the definition
      -->
      <!ELEMENT unknown EMPTY>

      <!--
        The fixed element defines a fixed date
      -->
      <!ELEMENT fixed EMPTY>
      <!ATTLIST fixed 
	        month (%months;) #REQUIRED
	        day CDATA #REQUIRED>

      <!--
        The Daylight Saving Time (dst) definition
        action defines whether the DST starts or whether the DST ends
      -->
      <!ELEMENT dst EMPTY>
      <!ATTLIST dst
                timezone CDATA #REQUIRED
                action (start|end) #IMPLIED>

      <!--
        This is the startdate of Easter
        Western churches use the Gregorian Calendar to calculate the date
        of Easter and Eastern Orthodox churches use the Julian Calendar
      -->
      <!ELEMENT easter EMPTY>
      <!ATTLIST easter
                church (western|eastern) "western">

      <!--
        This is the startdate of the 1st advent
      -->
      <!ELEMENT advent EMPTY>

      <!--
        http://en.wikipedia.org/wiki/Equinox
        "March equinox" and "September equinox"
        Names avoid the classical Northern Hemisphere bias implied by the
        assumption that March is in springtime and September is in autumn;
        only true for those in the Northern Hemisphere but actually the
        complete opposite for dwellers in the Southern Hemisphere.
      -->          
      <!ELEMENT equinox EMPTY>
      <!ATTLIST equinox
                month (March|September) #REQUIRED
                timezone CDATA #REQUIRED>
          
      <!--
        http://en.wikipedia.org/wiki/Solstice
      -->
      <!ELEMENT solstice EMPTY>
      <!ATTLIST solstice
                month (June|December) #REQUIRED
                timezone CDATA #REQUIRED>

		<!--
          Lunisolar
        -->
		<!ELEMENT lunisolar EMPTY>
		<!ATTLIST lunisolar
				month CDATA #REQUIRED
				day CDATA #REQUIRED>


      <!--
        The rule defines the nth weekday of a month
      -->
      <!ELEMENT rule EMPTY>
      <!ATTLIST rule
                nth (%nth;) #REQUIRED
                weekday (%weekdays;) #REQUIRED
                month (%months;) #REQUIRED>
      <!--
        The add modifier
        the "add" property value can become positive or negative
      -->
      <!ELEMENT add EMPTY>
      <!ATTLIST add
                days CDATA #REQUIRED>
        
      <!--
        The goto modifier
        moves to the next, previous or nearest weekday
        the direction can become
        nearest           - the nearest weekday, go not more than 3 days
                            in one direction
        next              - the next weekday
        nextinclusive     - a goto action happens only if the current
                            weekday is not the specified weekday
        previous          - the previous weekday
        previousinclusive - a goto action happens only if the current
                            weekday is not the specified weekday
      -->
      <!ELEMENT goto EMPTY>
      <!ATTLIST goto
                weekday (%weekdays;) #REQUIRED
                direction (%directions;) "nearest">

=== jonelo/xml-holidays/xml/holidays_pt.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!--
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="PT">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Portugal -->

    <default language="pt"/>

    <holiday>
        <description language="pt" name="Ano Novo"/>
        <description language="en" name="New Year's Day" type="public holiday"/>
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="en" name="Carnival"/>
        <import id="Carnival"/>
    </holiday>

    <holiday>
        <description language="en" name="Begin Daylight Saving Time"/>
        <definition>
            <dst timezone="Europe/Lisbon" action="start"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Sexta-Feira Santa"/>
        <description language="en" name="Good Friday" type="public holiday"/>
        <definition>
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="pt" name="Páscoa"/>
        <description language="en" name="Easter Sunday" type="public holiday"/>
        <import id="Easter Sunday"/>
    </holiday>
    
    <!-- Celebrates the 1974 Revolution that ended the 
         Dictatorship and started Democracy -->
    <holiday>
        <description language="pt" name="Dia da Liberdade"/>
        <description language="en" name="Freedom Day" type="public holiday"/>
        <definition firstyear="1974">
        	<fixed month="April" day="25" />
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Dia do Trabalhador"/>
        <description language="en" name="Labour Day" type="public holiday"/>
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Corpo de Deus"/>
        <description language="en" name="Corpus Christi" type="public holiday"/>
        <definition>
            <easter/>
            <add days="+60"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Dia de Portugal, de Camões e das Comunidades Portuguesas"/>
        <description language="en" name="Portugal Day" type="public holiday"/>
        <definition firstyear="1580">
        	<fixed month="June" day="10" />
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Assunção de Nossa Senhora"/>
        <description language="en" name="Assumption of Mary" type="public holiday"/>
        <definition>
            <fixed month="August" day="15"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Implantação da República"/>
        <description language="en" name="Republic Day" type="public holiday"/>
        <definition firstyear="1910">
        	<fixed month="October" day="5" />
        </definition>
    </holiday>

    <holiday>
        <description language="en" name="End Daylight Saving Time"/>
        <definition>
            <dst timezone="Europe/Lisbon" action="end"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Todos os Santos"/>
        <description language="en" name="All Saint's Day" type="public holiday"/>
        <import id="All Saint's Day"/>
    </holiday>

    <holiday>
        <description language="pt" name="Restauração da Independência"/>
        <description language="en" name="Restoration of Independence"/>
        <definition>
            <fixed month="December" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Imaculada Conceição"/>
        <description language="en" name="Immaculate Conception's day" type="public holiday"/>
        <definition>
            <fixed month="December" day="8"/>
        </definition>
    </holiday>

    <holiday>
        <description language="pt" name="Natal"/>
        <description language="en" name="Christmas Day" type="public holiday"/>
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>

</holidays>

=== jonelo/xml-holidays/xml/holidays_am.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="AM">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Armenia 
         http://www.armeniadiaspora.com/travel/holidays.html
    -->

    <default language="hy"/>

    <holiday>
        <description language="hy" name="Ամանօր" type="public"/>
        <description language="en" name="New Year's Day" type="public"/>
        <import id="New Year's Day"/>
    </holiday>

    <holiday>
        <description language="hy" name="Նախածննդյան տոներ" type="public"/>
        <description language="en" name="Christmas Eve" type="public"/>
        <definition>
            <fixed day="5" month="January"/>
        </definition>
    </holiday>

    <holiday>
        <description language="hy" name="Սուրբ Ծնունդ" type="public"/>
        <description language="en" name="Christmas Day" type="public"/>
        <definition>
            <fixed day="6" month="January"/>
        </definition>
    </holiday>

    <holiday>
        <description language="hy" name="Սուրբ Ծննդյան և Հայտնության տոնին հաջորդող` Մեռելոց հիշատակի օր" type="public"/>
        <description language="en" name="The day of commemoration of all dead people after Christmas Day" type="public"/>
        <definition>
            <fixed day="7" month="January"/>
        </definition>
    </holiday>

    <!-- In celebration of Armenian Army formation on that day in 1992 -->
    <holiday>
        <description language="hy" name="Բանակի օր" type="public"/>
        <description language="en" name="Army Day" type="public"/>
        <definition firstyear="1992">
            <fixed day="28" month="January"/>
        </definition>
    </holiday> 

    <!-- https://armeniadiscovery.com/en/articles/march-eight-how-armenians-celebrate-it -->
    <holiday>
        <description language="hy" name="Կանանց տոն" type="public"/>
        <description language="en" name="International Women's Day" type="public"/>
        <definition firstyear="1921">
            <fixed day="8" month="March"/>
        </definition>
    </holiday>

    <!-- Armenian Genocide in 1915
         See also http://aglobalworld.com/holidays-around-the-world/armenian-genocide-memorial-day-armenia/
    -->
    <holiday>
        <description language="hy" name="Եղեռնի զոհերի հիշատակի օր" type="public"/>
        <description language="en" name="Genocide Remembrance Day" type="public"/>
        <definition firstyear="1915">
            <fixed day="24" month="April"/>
        </definition>
    </holiday>
    
    <!--
         See also http://aglobalworld.com/holidays-around-the-world/victory-peace-day-armenia/
         "Armenia participated in World War II as part of the Soviet Union [...]
         It is a day to celebrate and remember the victory over the Nazi forces that capitulated on May 8, 1945
         during World War II."
     -->
    <holiday>
        <description language="hy" name="Հաղթանակի եւ Խաղաղության տոն" type="public"/>
        <description language="en" name="Victory and Peace Day" type="public"/>
        <definition firstyear="1945">
            <fixed day="9" month="May"/>
        </definition>
    </holiday>
    
    <!-- Establishment of the Democratic Republic of Armenia
         See also http://aglobalworld.com/holidays-around-the-world/republic-day-armenia/
    -->
    <holiday>
        <description language="hy" name="Հանրապետության օր" type="public"/>
        <description language="en" name="Republic Day" type="public"/>
        <definition firstyear="1918">
            <fixed day="28" month="May"/>
        </definition>
    </holiday>

    <holiday>
        <description language="hy" name="Սահմանադրության օր" type="public"/>
        <description language="en" name="Constitution Day" type="public"/>
        <definition firstyear="1995">
            <fixed day="5" month="July"/>
        </definition>
    </holiday>

    <!-- From the Soviet Union in 1991 -->
    <holiday>
        <description language="hy" name="Անկախության օր" type="public"/>
        <description language="en" name="Independence Day" type="public"/>
        <definition firstyear="1991">
            <fixed day="21" month="September"/>
        </definition>
    </holiday>
    
    <!-- A devastating earthquake in 1988 killed thousands of people and
         destroyed most of the Republic’s infrastructure. -->
    <holiday>
        <description language="hy" name="Երկրաշարժի զոհերի հիշատակի օր" type="public"/>
        <description language="en" name="1988 Earthquake Memorial Day (Spitak Remembrance Day)" type="public"/>
        <definition firstyear="1988">
            <fixed day="7" month="December"/>
        </definition>
    </holiday>
    
    <!-- Vardavar is celebrated 98 days (14 weeks) after Easter. -->
    <holiday>
        <description language="hy" name="Վարդևար"/>
        <description language="en" name="Vardevar"/>
        <definition>
            <easter/>
            <add days="98"/>
        </definition>
    </holiday>
    
</holidays>

=== jonelo/xml-holidays/xml/holidays_si.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!--
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
-->
<holidays country="SI">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Slovenia -->

    <default language="sl"/>

    <holiday>
        <description language="sl" name="novo leto"/>
        <description language="en" name="New Year's Day" type="state holiday, work-free"/>
        <definition>
            <fixed month="January" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="2. novo leto"/>
        <description language="en" name="New Year's Day" type="state holiday, work-free"/>
        <definition>
            <fixed month="January" day="2"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="Prešernov dan, slovenski kulturni praznik"/>
        <description language="en" name="The Slovenian Cultural Holiday" type="state holiday, work-free"/>
        <!-- established as the national cultural day in 1944, work-free since 1991. -->
        <definition firstyear="1944">
            <fixed month="February" day="8"/>
        </definition>
    </holiday>

    <holiday>
        <description language="en" name="Begin Daylight Saving Time"/>
        <definition>
            <dst timezone="Europe/Ljubljana" action="start"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="sl" name="velika noč in velikonočni ponedeljek"/>
        <description language="en" name="Easter Sunday" type="work-free day"/>
        <import id="Easter Sunday"/>
    </holiday>

    <holiday>
        <description language="sl" name="2. velika noč in velikonočni ponedeljek"/>
        <description language="en" name="Easter Monday" type="work-free day"/>
        <import id="Easter Monday"/>
    </holiday>

    <holiday>
        <description language="sl" name="dan upora proti okupatorju"/>
        <description language="en" name="Day of Uprising Against Occupation" type="state holiday, work-free"/>
        <definition>
            <fixed month="April" day="27"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="praznik dela"/>
        <description language="en" name="Labour Day" type="state holiday"/>
        <definition>
            <fixed month="May" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="2. praznik dela"/>
        <description language="en" name="2. Labour Day" type="state holiday"/>
        <definition>
            <fixed month="May" day="2"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="binkoštna nedelja"/>
        <description language="en" name="Pentecost" type="work-free day"/>
        <import id="Pentecost"/>
    </holiday>

    <holiday>
        <description language="sl" name="dan državnosti"/>
        <description language="en" name="Statehood Day" type="state holiday"/>
        <definition>
            <fixed month="June" day="25"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="Marijino vnebovzetje"/>
        <description language="en" name="Assumption Day" type="work-free day"/>
        <definition>
            <fixed month="August" day="15"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="dan združitve prekmurskih Slovencev z matičnim narodom po prvi svetovni vojni"/>
        <description language="en" name="Union of the Slovenians in Prekmurje with the mother nation after the First World War" type="state holiday, not work-free"/>
        <definition>
            <fixed month="August" day="17"/>
        </definition>
    </holiday>

    <holiday>
        <description language="en" name="End Daylight Saving Time"/>
        <definition>
            <dst timezone="Europe/Ljubljana" action="end"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="dan vrnitve Primorske k matični domovini"/>
        <description language="en" name="Reunion of Slovenian Littoral with the motherland" type="state holiday, not work-free"/>
        <definition>
            <fixed month="September" day="15"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="dan reformacije"/>
        <description language="en" name="Reformation Day" type="work-free day"/>
        <definition>
            <fixed month="October" day="15"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="dan spomina na mrtve"/>
        <description language="en" name="Remembrance day" type="state holiday, work-free"/>
        <definition>
            <fixed month="November" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="dan Rudolfa Maistra"/>
        <description language="en" name="Rudolf Maister Day" type="state holiday, not work-free"/>
        <definition>
            <fixed month="November" day="23"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="Božič"/>
        <description language="en" name="Christmas Day" type="work-free day"/>
        <definition>
            <fixed month="December" day="25"/>
        </definition>
    </holiday>

    <holiday>
        <description language="sl" name="dan samostojnosti in enotnosti"/>
        <description language="en" name="Independence and Unity Day" type="state holiday, work free"/>
        <!-- Commemorates the proclamation of the independence plebiscite results in 1990 -->
        <definition firstyear="1990">
            <fixed month="December" day="26"/>
        </definition>
    </holiday>

</holidays>

=== jonelo/xml-holidays/xml/holidays_it.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
-->
<holidays country="IT">
    <!-- Italy -->
    <!-- http://en.wikipedia.org/wiki/Holidays_in_Italy
         http://de.wikipedia.org/wiki/Feiertage_in_Italien
      -->

    <default language="it"/>

    <holiday>
        <description language="it" name="Capodanno"/>
        <description language="en" name="New Year's Day" type="public holiday"/>
        <import id="New Year's Day"/>
    </holiday>
    
    <holiday>
        <description language="it" name="Epifania"/>
        <description language="en" name="Epiphany" type="public holiday"/>
        <definition>
            <fixed day="6" month="January" />
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="Begin Daylight Saving Time"/>
        <definition>
            <dst timezone="Europe/Rome" action="start"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Pasqua"/>
        <description language="en" name="Easter Sunday" type="public holiday"/>
        <definition>
            <easter/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="LunedÃ¬ dell'Angelo, Pasquetta"/>
        <description language="en" name="Easter Monday" type="public holiday"/>
        <definition>
            <easter/>
            <add days="+1"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Festa della Liberazione"/>
        <description language="en" name="Anniversary of Liberation" type="public holiday"/>
        <definition firstyear="1945">
            <fixed day="25" month="April"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Festa dei Lavoratori"/>
        <description language="en" name="Labor Day" type="public holiday"/>
        <definition>
            <fixed day="1" month="May"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Festa della Repubblica"/>
        <description language="en" name="Republic Day" type="public holiday"/>
        <definition firstyear="1946">
            <fixed day="2" month="June"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="San Giovanni"/>
        <definition>
            <fixed day="24" month="June"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Assunzione (Ferragosto)"/>
        <description language="en" name="Ferragosto/Assumption Day" type="public holiday"/>
        <definition>
            <fixed day="15" month="August"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="End Daylight Saving Time"/>
        <definition>
            <dst timezone="Europe/Rome" action="end"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Ognissanti (Tutti i Santi)"/>
        <description language="en" name="All Saints" type="public holiday"/>
        <definition>
            <fixed day="1" month="November"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Il giorno dei morti"/>
        <description language="en" name="Day of the dead" type="public holiday"/>
        <definition>
            <fixed day="2" month="November"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Giorno della Vittoria"/>
        <description language="en" name="Victory Day" type="public holiday"/>
        <definition firstyear="1918">
            <fixed day="4" month="November"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Immacolata Concezione (Immacolata)"/>
        <description language="en" name="Immaculate Conception" type="public holiday"/>
        <definition>
            <fixed day="8" month="December"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Natale"/>
        <description language="en" name="Christmas Day" type="public holiday"/>
        <definition>
            <fixed day="25" month="December"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="Santo Stefano"/>
        <description language="en" name="St Stephen's Day" type="public holiday"/>
        <definition>
            <fixed day="26" month="December"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="it" name="San Silvestro"/>
        <description language="en" name="New Year's Eve"/>
        <definition>
            <fixed day="31" month="December"/>
        </definition>
    </holiday>
</holidays>
