=== jonelo/xml-holidays/xml/holidays.dtd
<!-- 
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
 -->
 
<!ENTITY % months "January | February | March | April |
                   May | June | July | August | September |
                   October | November | December">
<!ENTITY % weekdays "Monday | Tuesday | Wednesday | Thursday |
                     Friday | Saturday | Sunday">
<!ENTITY % nth "First | Second | Third | Fourth | Last">
<!ENTITY % startdate "fixed | easter | advent | rule | dst |
                      equinox | solstice | lunisolar">
<!ENTITY % modifiers "add | goto">
<!ENTITY % directions "nearest | next | nextinclusive | previous | previousinclusive">

<!--
  The element called holidays must have at least one element called holiday
  "country"         the ID of the country
                    use ISO 3166-1-alpha-2 code in uppercase characters
                    if applicable
  -->
<!ELEMENT holidays (default+,holiday+)>
<!ATTLIST holidays
          country CDATA #REQUIRED>

   <!--
     The default element specifies a language which is common in a country
     "language"      specify the language for a holiday name.
                     Use ISO 639-1-alpha-2 code in lowercase characters
                     if applicable.
    -->
   <!ELEMENT default EMPTY>
   <!ATTLIST default
             language CDATA #REQUIRED>
   <!--
     A holiday can have one import element or a combination of both definitions
     and code
     "id"            an optional identification (holiday is usually identified
                     by the holiday name)
     "valid"         indicates whether the holiday is still valid or not
                     (use false if it is a history or obsolete holiday)
   -->
   <!ELEMENT holiday (description+,(import|definition+))>
   <!ATTLIST holiday
             id CDATA #IMPLIED
             valid (true|false) "true">

      <!-- 
        "language"   the language in which the name of the holiday is expressed
        "name"       the name of the holiday expressed in "language"
        "type"       free text, it should further describe the type of the
                     holiday (e.g. legal holiday, de facto legal holiday,
                     katholic, etc.)
        "region"     free text, the region of the holiday if applicable
        -->
      <!ELEMENT description EMPTY>
      <!ATTLIST description
                language CDATA #REQUIRED
                name CDATA #REQUIRED
                type CDATA #IMPLIED
                region CDATA #IMPLIED>

      <!--
        An import element imports the definitions of a holiday from the
        file called holidays_shared.xml
      -->
      <!ELEMENT import EMPTY>
      <!ATTLIST import
                id CDATA #REQUIRED>

      <!--
        The definition is either
        * undefined or 
        * unkonwn or
        * it is a startdate, followed by a modifier or a condition
      -->
      <!ELEMENT definition (undefined | unknown | ((%startdate;),(%modifiers; | condition)*))>
      <!--
        year       the year when the holiday is valid,
                   same as if firstyear equals lastyear
                   the frequency, firstyear and lastyear are being ignored
                   if year is set
        firstyear  the first year when the holiday is valid (inclusively)
        lastyear   the last year when the holiday was valid (inclusively)
        frequency  how many years must pass, until the next year is valid?
                   (the actual start of the frequency depends on the firstyear
                   respectively on the lastyear if firstyear is not set)
        ifweekday  only valid if the date is on a particular weekday.
        ifdaytype  only valid if the type of the date is of a particular type.
        ifdayofmonth only valid if the day is a particular day of a month
      -->
      <!ATTLIST definition
                year CDATA #IMPLIED
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED
                frequency CDATA #IMPLIED>
      <!--
        a condition can be undefined, unknown or it can have multiple modifiers
      -->
      <!ELEMENT condition (undefined | unknown | (%modifiers;)*)>
      <!ATTLIST condition
                ifweekday (%weekdays;) #IMPLIED
                ifdaytype CDATA #IMPLIED
                ifdayname CDATA #IMPLIED
                ifdayofmonth CDATA #IMPLIED
                language CDATA #IMPLIED>
          
      <!--
        The undefined element says that a holiday wasn't/isn't
        defined during the years of the definition
      -->
      <!ELEMENT undefined EMPTY>
          
      <!--
        The empty element defines that we don't know the definition
      -->
      <!ELEMENT unknown EMPTY>

      <!--
        The fixed element defines a fixed date
      -->
      <!ELEMENT fixed EMPTY>
      <!ATTLIST fixed 
	        month (%months;) #REQUIRED
	        day CDATA #REQUIRED>

      <!--
        The Daylight Saving Time (dst) definition
        action defines whether the DST starts or whether the DST ends
      -->
      <!ELEMENT dst EMPTY>
      <!ATTLIST dst
                timezone CDATA #REQUIRED
                action (start|end) #IMPLIED>

      <!--
        This is the startdate of Easter
        Western churches use the Gregorian Calendar to calculate the date
        of Easter and Eastern Orthodox churches use the Julian Calendar
      -->
      <!ELEMENT easter EMPTY>
      <!ATTLIST easter
                church (western|eastern) "western">

      <!--
        This is the startdate of the 1st advent
      -->
      <!ELEMENT advent EMPTY>

      <!--
        http://en.wikipedia.org/wiki/Equinox
        "March equinox" and "September equinox"
        Names avoid the classical Northern Hemisphere bias implied by the
        assumption that March is in springtime and September is in autumn;
        only true for those in the Northern Hemisphere but actually the
        complete opposite for dwellers in the Southern Hemisphere.
      -->          
      <!ELEMENT equinox EMPTY>
      <!ATTLIST equinox
                month (March|September) #REQUIRED
                timezone CDATA #REQUIRED>
          
      <!--
        http://en.wikipedia.org/wiki/Solstice
      -->
      <!ELEMENT solstice EMPTY>
      <!ATTLIST solstice
                month (June|December) #REQUIRED
                timezone CDATA #REQUIRED>

		<!--
          Lunisolar
        -->
		<!ELEMENT lunisolar EMPTY>
		<!ATTLIST lunisolar
				month CDATA #REQUIRED
				day CDATA #REQUIRED>


      <!--
        The rule defines the nth weekday of a month
      -->
      <!ELEMENT rule EMPTY>
      <!ATTLIST rule
                nth (%nth;) #REQUIRED
                weekday (%weekdays;) #REQUIRED
                month (%months;) #REQUIRED>
      <!--
        The add modifier
        the "add" property value can become positive or negative
      -->
      <!ELEMENT add EMPTY>
      <!ATTLIST add
                days CDATA #REQUIRED>
        
      <!--
        The goto modifier
        moves to the next, previous or nearest weekday
        the direction can become
        nearest           - the nearest weekday, go not more than 3 days
                            in one direction
        next              - the next weekday
        nextinclusive     - a goto action happens only if the current
                            weekday is not the specified weekday
        previous          - the previous weekday
        previousinclusive - a goto action happens only if the current
                            weekday is not the specified weekday
      -->
      <!ELEMENT goto EMPTY>
      <!ATTLIST goto
                weekday (%weekdays;) #REQUIRED
                direction (%directions;) "nearest">

=== jonelo/xml-holidays/xml/holidays_co.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
-->
<holidays country="CO">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Colombia 
         http://es.wikipedia.org/wiki/Fiestas_de_Colombia -->

    <default language="es"/>

    <holiday>
        <description language="es" name="Año Nuevo"/>
        <description language="en" name="New Year's Day" type="public holiday"/>
        <import id="New Year's Day"/>
    </holiday>
    
    <holiday>
        <description language="es" name="Día de los Reyes Magos"/>
        <description language="en" name="Epiphany" type="public holiday"/>
        <definition>
            <fixed day="6" month="January"/>
            <!--
              Movable holiday: when it does not fall on a Monday,
              the holiday is observed on the following Monday.
            -->
            <condition ifweekday="Tuesday">
                <add days="6"/>
            </condition>
            <condition ifweekday="Wednesday">
                <add days="5"/>
            </condition>
            <condition ifweekday="Thursday">
                <add days="4"/>
            </condition>
            <condition ifweekday="Friday">
                <add days="3"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="2"/>
            </condition>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
        </definition>
    </holiday>
    
    
    <holiday>
        <description language="es" name="Día del Maestro"/>
        <description language="en" name="Teacher's Day" type="public holiday"/>
        <definition>
            <fixed day="15" month="May"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="es" name="Día de San José"/>
        <description language="en" name="Saint Joseph's Day" type="public holiday"/>
        <definition>
            <fixed day="19" month="March"/>
            <!--
              Movable holiday: when they do not fall on a Monday,
              the holiday is observed on the following Monday.
            -->
            <condition ifweekday="Tuesday">
                <add days="6"/>
            </condition>
            <condition ifweekday="Wednesday">
                <add days="5"/>
            </condition>
            <condition ifweekday="Thursday">
                <add days="4"/>
            </condition>
            <condition ifweekday="Friday">
                <add days="3"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="2"/>
            </condition>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="Jueves Santo" type="public holiday"/>
        <import id="Maundy Thursday"/>
    </holiday>
    
    <holiday>
        <description language="es" name="Viernes Santo"/>
        <description language="en" name="Good Friday" type="public holiday"/>
        <import id="Good Friday"/>
    </holiday>
    
    <holiday>
        <description language="en" name="Labor Day" type="public holiday"/>
        <description language="es" name="Primero de Mayo"/>
        <definition>
            <fixed day="1" month="May"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="es" name="Ascensión"/>
        <description language="en" name="Ascension" type="public holiday"/>
        <import id="Ascension of Jesus"/>
    </holiday>
    
    <holiday>
        <description language="en" name="Corpus Christi" type="public holiday"/>
        <import id="Corpus Christi"/>
    </holiday>
    
    <holiday>
        <description language="es" name="Sagrado Corazón"/>
        <description language="en" name="Sacred Heart" type="public holiday"/>
        <definition>
            <!-- observed the Monday ten weeks and a day after Easter Sunday -->
            <easter/>
            <add days="71"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="es" name="San Pedro y San Pablo"/>
        <description language="en" name="Saint Peter and Saint Paul" type="public holiday"/>
        <definition>
            <fixed day="29" month="June"/>
            <!--
              Movable holiday: when it does not fall on a Monday,
              the holiday is observed on the following Monday.
            -->
            <condition ifweekday="Tuesday">
                <add days="6"/>
            </condition>
            <condition ifweekday="Wednesday">
                <add days="5"/>
            </condition>
            <condition ifweekday="Thursday">
                <add days="4"/>
            </condition>
            <condition ifweekday="Friday">
                <add days="3"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="2"/>
            </condition>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="Independence Day" type="public holiday"/>
        <definition>
            <fixed day="20" month="July"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="Battle of Boyacá" type="public holiday"/>
        <definition>
            <fixed day="7" month="August"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="es" name="La Asunción"/>
        <description language="en" name="Assumption of Mary" type="public holiday"/>
        <definition>
            <fixed day="15" month="August"/>
            <!--
              Movable holiday: when it does not fall on a Monday,
              the holiday is observed on the following Monday.
            -->
            <condition ifweekday="Tuesday">
                <add days="6"/>
            </condition>
            <condition ifweekday="Wednesday">
                <add days="5"/>
            </condition>
            <condition ifweekday="Thursday">
                <add days="4"/>
            </condition>
            <condition ifweekday="Friday">
                <add days="3"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="2"/>
            </condition>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="Columbus Day" type="public holiday"/>
        <description language="es" name="Día de la Raza"/>
        <definition>
            <fixed day="12" month="October"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="All Saints' Day" type="public holiday"/>
        <definition>
            <fixed day="1" month="November"/>
            <!--
              Movable holiday: when it does not fall on a Monday,
              the holiday is observed on the following Monday.
            -->
            <condition ifweekday="Tuesday">
                <add days="6"/>
            </condition>
            <condition ifweekday="Wednesday">
                <add days="5"/>
            </condition>
            <condition ifweekday="Thursday">
                <add days="4"/>
            </condition>
            <condition ifweekday="Friday">
                <add days="3"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="2"/>
            </condition>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="Independence of Cartagena City" type="public holiday"/>
        <definition>
            <fixed day="11" month="November"/>
            <!--
              Movable holiday: when it does not fall on a Monday,
              the holiday is observed on the following Monday.
            -->
            <condition ifweekday="Tuesday">
                <add days="6"/>
            </condition>
            <condition ifweekday="Wednesday">
                <add days="5"/>
            </condition>
            <condition ifweekday="Thursday">
                <add days="4"/>
            </condition>
            <condition ifweekday="Friday">
                <add days="3"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="2"/>
            </condition>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
        </definition>
    </holiday>
    
    <holiday>
        <description language="es" name="La Inmaculada Concepción"/>
        <description language="en" name="Immaculate Conception" type="public holiday"/>
        <definition>
            <fixed day="8" month="December"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="es" name="Navidad"/>
        <description language="en" name="Christmas Day" type="public holiday"/>
        <import id="Christmas Day"/>
    </holiday>
    
    <holiday>
        <description language="en" name="Begin Daylight Saving Time (DST)"/>
        <definition>
            <dst timezone="America/Bogota" action="start"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="End Daylight Saving Time (DST)"/>
        <definition>
            <dst timezone="America/Bogota" action="end"/>
        </definition>
    </holiday>
    
</holidays>

=== jonelo/xml-holidays/xml/holidays_ru.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!--
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
-->
<!-- Russia -->
<holidays country="RU">
    <!-- http://en.wikipedia.org/wiki/Public_holidays_in_Russia
    Russland http://www.russlandjournal.de/russland/reiseinformationen/feiertage/-->
	<!-- generell gilt: fällt ein Feiertag auf Samstag oder Sonntag wird der Feiertag auf einen
	     Arbeitstag verlegt !! -->
	<!-- viele Geschäfte bleiben vom 31.12 - 7.1 durchgehend geschlossen 
        If the date of observance falls on a Saturday or Sunday, the following Monday will be a day off in lieu of the holiday
        -->

    <default language="ru"/>

    <holiday>
        <description language="ru" name="Новый Год / Novy God"/>
        <description language="en" name="New Year's Day" type="public holiday"/>
        <definition>
            <fixed month="January" day="1"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="Рождество / Rozhdestvo"/>
        <description language="en" name="Orthodox Christmas Day" type="public holiday"/>
        <definition>
            <fixed month="January" day="7"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День святого Валентина"/>
        <description language="en" name="Valentine's Day"/>
        <description language="de" name="Valentinstag"/>
         <definition>
            <fixed month="February" day="14"/>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="Масленица / Maslenitsa"/>
        <description language="en" name="Carnival"/>
        <description language="de" name="Russische Fastnacht"/>
        <definition>
            <easter church="eastern"/>
            <add days="-47"/>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День Защитника Отечества / Den' zashchitnika Otechestva" type="public holiday"/>
        <description language="en" name="Defender of the Fatherland Day"/>
        <definition>
            <fixed month="February" day="23"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>
    
    <holiday>
        <description language="ru" name="Международный Женский День"/>
        <description language="en" name="International Women's Day" type="public holiday"/>
        <description language="de" name="Weltfrauentag"/>
        <definition>
            <fixed month="March" day="8"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День весны и труда"/>
        <description language="en" name="Spring and Labour Day" type="public holiday"/>
        <description language="de" name="Tag des Frühlings und der Arbeit"/>
        <definition>
            <fixed month="May" day="1"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День Победы"/>
        <description language="de" name="Tag des Sieges über den Faschismus 1945"/>
        <description language="en" name="Victory Day" type="public holiday"/>
        <definition firstyear="1945">
            <fixed month="May" day="9"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День России"/>
        <description language="en" name="Russia Day" type="public holiday"/>
        <description language="de" name="Tag Russlands"/>
        <definition>
            <fixed month="June" day="12"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День народного единства"/>
        <description language="de" name="Tag der Einheit des Volkes "/>
        <description language="en" name="Unity Day" type="public holiday"/>
        <definition firstyear="2005">
            <fixed month="November" day="4"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="Пасха"/>
        <description language="en" name="Easter"/>
        <description language="de" name="Russisch-Orthodox Ostern"/>
        <definition>
            <easter church="eastern"/>
        </definition>
    </holiday>

    <holiday>
        <description language="ru" name="День Знамени"/>
        <description language="de" name="Tag der Nationalflagge"/>
        <definition>
            <fixed month="August" day="22"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="ru" name="День Конституции"/>
        <description language="de" name="Tag der Verfassung"/>
        <definition>
            <fixed month="December" day="12"/>
        </definition>
    </holiday>
</holidays>
