=== jonelo/xml-holidays/xml/holidays.dtd
<!-- 
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
 -->
 
<!ENTITY % months "January | February | March | April |
                   May | June | July | August | September |
                   October | November | December">
<!ENTITY % weekdays "Monday | Tuesday | Wednesday | Thursday |
                     Friday | Saturday | Sunday">
<!ENTITY % nth "First | Second | Third | Fourth | Last">
<!ENTITY % startdate "fixed | easter | advent | rule | dst |
                      equinox | solstice | lunisolar">
<!ENTITY % modifiers "add | goto">
<!ENTITY % directions "nearest | next | nextinclusive | previous | previousinclusive">

<!--
  The element called holidays must have at least one element called holiday
  "country"         the ID of the country
                    use ISO 3166-1-alpha-2 code in uppercase characters
                    if applicable
  -->
<!ELEMENT holidays (default+,holiday+)>
<!ATTLIST holidays
          country CDATA #REQUIRED>

   <!--
     The default element specifies a language which is common in a country
     "language"      specify the language for a holiday name.
                     Use ISO 639-1-alpha-2 code in lowercase characters
                     if applicable.
    -->
   <!ELEMENT default EMPTY>
   <!ATTLIST default
             language CDATA #REQUIRED>
   <!--
     A holiday can have one import element or a combination of both definitions
     and code
     "id"            an optional identification (holiday is usually identified
                     by the holiday name)
     "valid"         indicates whether the holiday is still valid or not
                     (use false if it is a history or obsolete holiday)
   -->
   <!ELEMENT holiday (description+,(import|definition+))>
   <!ATTLIST holiday
             id CDATA #IMPLIED
             valid (true|false) "true">

      <!-- 
        "language"   the language in which the name of the holiday is expressed
        "name"       the name of the holiday expressed in "language"
        "type"       free text, it should further describe the type of the
                     holiday (e.g. legal holiday, de facto legal holiday,
                     katholic, etc.)
        "region"     free text, the region of the holiday if applicable
        -->
      <!ELEMENT description EMPTY>
      <!ATTLIST description
                language CDATA #REQUIRED
                name CDATA #REQUIRED
                type CDATA #IMPLIED
                region CDATA #IMPLIED>

      <!--
        An import element imports the definitions of a holiday from the
        file called holidays_shared.xml
      -->
      <!ELEMENT import EMPTY>
      <!ATTLIST import
                id CDATA #REQUIRED>

      <!--
        The definition is either
        * undefined or 
        * unkonwn or
        * it is a startdate, followed by a modifier or a condition
      -->
      <!ELEMENT definition (undefined | unknown | ((%startdate;),(%modifiers; | condition)*))>
      <!--
        year       the year when the holiday is valid,
                   same as if firstyear equals lastyear
                   the frequency, firstyear and lastyear are being ignored
                   if year is set
        firstyear  the first year when the holiday is valid (inclusively)
        lastyear   the last year when the holiday was valid (inclusively)
        frequency  how many years must pass, until the next year is valid?
                   (the actual start of the frequency depends on the firstyear
                   respectively on the lastyear if firstyear is not set)
        ifweekday  only valid if the date is on a particular weekday.
        ifdaytype  only valid if the type of the date is of a particular type.
        ifdayofmonth only valid if the day is a particular day of a month
      -->
      <!ATTLIST definition
                year CDATA #IMPLIED
                firstyear CDATA #IMPLIED
                lastyear CDATA #IMPLIED
                frequency CDATA #IMPLIED>
      <!--
        a condition can be undefined, unknown or it can have multiple modifiers
      -->
      <!ELEMENT condition (undefined | unknown | (%modifiers;)*)>
      <!ATTLIST condition
                ifweekday (%weekdays;) #IMPLIED
                ifdaytype CDATA #IMPLIED
                ifdayname CDATA #IMPLIED
                ifdayofmonth CDATA #IMPLIED
                language CDATA #IMPLIED>
          
      <!--
        The undefined element says that a holiday wasn't/isn't
        defined during the years of the definition
      -->
      <!ELEMENT undefined EMPTY>
          
      <!--
        The empty element defines that we don't know the definition
      -->
      <!ELEMENT unknown EMPTY>

      <!--
        The fixed element defines a fixed date
      -->
      <!ELEMENT fixed EMPTY>
      <!ATTLIST fixed 
	        month (%months;) #REQUIRED
	        day CDATA #REQUIRED>

      <!--
        The Daylight Saving Time (dst) definition
        action defines whether the DST starts or whether the DST ends
      -->
      <!ELEMENT dst EMPTY>
      <!ATTLIST dst
                timezone CDATA #REQUIRED
                action (start|end) #IMPLIED>

      <!--
        This is the startdate of Easter
        Western churches use the Gregorian Calendar to calculate the date
        of Easter and Eastern Orthodox churches use the Julian Calendar
      -->
      <!ELEMENT easter EMPTY>
      <!ATTLIST easter
                church (western|eastern) "western">

      <!--
        This is the startdate of the 1st advent
      -->
      <!ELEMENT advent EMPTY>

      <!--
        http://en.wikipedia.org/wiki/Equinox
        "March equinox" and "September equinox"
        Names avoid the classical Northern Hemisphere bias implied by the
        assumption that March is in springtime and September is in autumn;
        only true for those in the Northern Hemisphere but actually the
        complete opposite for dwellers in the Southern Hemisphere.
      -->          
      <!ELEMENT equinox EMPTY>
      <!ATTLIST equinox
                month (March|September) #REQUIRED
                timezone CDATA #REQUIRED>
          
      <!--
        http://en.wikipedia.org/wiki/Solstice
      -->
      <!ELEMENT solstice EMPTY>
      <!ATTLIST solstice
                month (June|December) #REQUIRED
                timezone CDATA #REQUIRED>

		<!--
          Lunisolar
        -->
		<!ELEMENT lunisolar EMPTY>
		<!ATTLIST lunisolar
				month CDATA #REQUIRED
				day CDATA #REQUIRED>


      <!--
        The rule defines the nth weekday of a month
      -->
      <!ELEMENT rule EMPTY>
      <!ATTLIST rule
                nth (%nth;) #REQUIRED
                weekday (%weekdays;) #REQUIRED
                month (%months;) #REQUIRED>
      <!--
        The add modifier
        the "add" property value can become positive or negative
      -->
      <!ELEMENT add EMPTY>
      <!ATTLIST add
                days CDATA #REQUIRED>
        
      <!--
        The goto modifier
        moves to the next, previous or nearest weekday
        the direction can become
        nearest           - the nearest weekday, go not more than 3 days
                            in one direction
        next              - the next weekday
        nextinclusive     - a goto action happens only if the current
                            weekday is not the specified weekday
        previous          - the previous weekday
        previousinclusive - a goto action happens only if the current
                            weekday is not the specified weekday
      -->
      <!ELEMENT goto EMPTY>
      <!ATTLIST goto
                weekday (%weekdays;) #REQUIRED
                direction (%directions;) "nearest">

=== jonelo/xml-holidays/xml/holidays_ua.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!--
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
-->
<!-- Ukraine -->
<holidays country="UA">
    <!-- https://en.wikipedia.org/wiki/Public_holidays_in_Ukraine -->

    <default language="uk"/> <!-- Ukrainian -->

    <holiday>
        <description language="uk" name="Новий Рік"/>
        <description language="ru" name="Новый Год / Novy God"/>
        <description language="en" name="New Year's Day" type="public holiday"/>
        <definition>
            <fixed month="January" day="1"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Різдво Христове"/>
        <description language="ru" name="Рождество / Rozhdestvo"/>
        <description language="en" name="Orthodox Christmas Day" type="public holiday"/>
        <description language="de" name="Orthodoxer Weihnachtstag" type="public holiday"/>
        <definition>
            <fixed month="January" day="7"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Міжнародний жіночий день"/>
        <description language="ru" name="Международный Женский День"/>
        <description language="en" name="International Women's Day" type="public holiday"/>
        <description language="de" name="Weltfrauentag"/>
        <definition>
            <fixed month="March" day="8"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Великдень"/>
        <description language="en" name="Orthodox Easter"/>
        <description language="de" name="Orthodoxer Ostersonntag"/>
        <definition>
            <easter church="eastern"/>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Великодній понеділок"/>
        <description language="en" name="Orthodox Easter Monday"/>
        <description language="de" name="Orthodoxer Oster(montag)"/>
        <definition>
            <easter church="eastern"/>
            <add days="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Трійця"/>
        <description language="en" name="Orthodox Pentecost"/>
        <description language="de" name="Orthodoxer Pfingstsonntag"/>
        <definition>
            <easter church="eastern"/>
            <add days="49"/>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Трійця (понеділок)"/>
        <description language="en" name="Orthodox Pentecost Monday"/>
        <description language="de" name="Orthodoxer Pfingstmontag"/>
        <definition>
            <easter church="eastern"/>
            <add days="50"/>
        </definition>
    </holiday>


    <holiday>
        <description language="uk" name="День праці"/>
        <description language="en" name="International Workers Day" type="public holiday"/>
        <description language="de" name="Tag der Arbeit"/>
        <definition>
            <fixed month="May" day="1"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="День перемоги над нацизмом у Другій світовій війні"/>
        <description language="en" name="Victory Day over Nazism in World War II" type="public holiday"/>
        <description language="de" name="Tag des Sieges über den Nationalsozialismus im 2. Weltkrieg"/>
        <definition>
            <fixed month="May" day="9"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="День Конституції України"/>
        <description language="en" name="Constitution Day" type="public holiday"/>
        <description language="de" name="Tag der Verfassung"/>
        <definition>
            <fixed month="June" day="28"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="День Незалежности України"/>
        <description language="en" name="Independence Day" type="public holiday"/> <!-- From the USSR in 1991 -->
        <description language="de" name="Unabhängigkeitstag"/>
        <definition firstyear="1991">
            <fixed month="August" day="24"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="День захисників і захисниць України"/>
        <description language="en" name="Defenders and Defendresses of Ukraine Day" type="public holiday"/> <!-- From the USSR in 1991 -->
        <description language="de" name="Tag der Verteidiger und Verteidigerinnen der Ukraine"/>
        <definition firstyear="2015">
            <fixed month="October" day="14"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

    <holiday>
        <description language="uk" name="Різдво Христове "/>
        <description language="en" name="Christmas" type="public holiday"/>
        <description language="de" name="Weihnachtstag"/>
        <definition firstyear="2017">
            <fixed month="December" day="25"/>
            <condition ifweekday="Sunday">
                <add days="1"/>
            </condition>
            <condition ifweekday="Saturday">
                <add days="+2"/>
            </condition>
        </definition>
    </holiday>

</holidays>

=== jonelo/xml-holidays/xml/holidays_int.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    http://xml-holidays.sourceforge.net/
    Thank you for keeping the comment.
-->
<holidays country="INT">

    <default language="en"/>
    
    <!-- January -->
    
    <holiday>
        <!-- https://en.wikipedia.org/wiki/World_Leprosy_Day -->
        <description language="en" name="World Leprosy Day"/>
        <!-- https://de.wikipedia.org/wiki/Welt-Lepra-Tag -->
        <description language="de" name="Welt-Lepra-Tag"/>
        <!-- https://it.wikipedia.org/wiki/Giornata_mondiale_per_i_malati_di_lebbra -->
        <description language="it" name="Giornata mondiale per i malati di lebbra"/>
        <!-- https://tr.wikipedia.org/wiki/Dünya_Cüzzam_Günü -->
        <description language="tr" name="Dünya Cüzzam Günü"/>
        <definition firstyear="1954">
            <rule nth="Last" weekday="Sunday" month="January"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="en" name="World Braille Day"/>
        <description language="de" name="Welt-Braille-Tag"/>
        <definition firstyear="2001">
            <fixed month="January" day="4"/>
        </definition>
    </holiday>
    
    <holiday>
        <!-- https://en.wikipedia.org/wiki/National_Hugging_Day -->
        <description language="en" name="National Hugging Day"/>
        <!-- https://de.wikipedia.org/wiki/Weltknuddeltag -->
        <description language="de" name="Weltknuddeltag"/>
        <!-- https://fr.wikipedia.org/wiki/Journée_internationale_des_câlins -->
        <description language="fr" name="Journée internationale des câlins"/>
        <!-- https://nl.wikipedia.org/wiki/Knuffeldag -->
        <description language="nl" name="Knuffeldag"/>
        <definition firstyear="1986">
            <fixed month="January" day="21"/>
        </definition>
    </holiday>
    
    <!-- February -->
    
    <holiday>
        <!-- https://futurezone.at/digital-life/der-erste-februar-ist-change-your-password-day/178.401.606 -->
        <description language="en" name="Change Your Password Day"/>
        
        <definition firstyear="2016">
            <fixed month="February" day="1"/>
        </definition>
    </holiday>

    <holiday>
        <description language="de" name="Weltkrebstag"/>
        <description language="en" name="World Cancer Day"/>

        <definition firstyear="2000">
            <fixed month="February" day="4"/>
        </definition>
    </holiday>


    <holiday>
        <!-- https://www.saferinternetday.org -->
        <description language="en" name="Safer Internet Day"/>
        <!-- https://de.wikipedia.org/wiki/Safer_Internet_Day -->
        <description language="de" name="Safer Internet Day"/>
        <!-- https://it.wikipedia.org/wiki/Safer_Internet_Day -->
        <description language="it" name="Safer Internet Day"/>
        
        <definition firstyear="2004">
            <!-- zweiter Tag der zweiten Woche des zweiten Monats -->
            <rule nth="Second" weekday="Sunday" month="February"/>
            <add days="-5"/>
        </definition>
        
    </holiday>
    
    <!-- March -->

    <holiday>
        <!-- https://de.wikipedia.org/wiki/Welttag_der_Meteorologie -->
        <description language="de" name="Welttag der Meteorologie"/>
        <!-- https://en.wikipedia.org/wiki/World_Meteorological_day -->
        <description language="en" name="World Meteorological day"/>
        <!-- https://es.wikipedia.org/wiki/D%C3%ADa_Meteorológico_Mundial -->
        <description language="es" name="Día Meteorológico Mundial"/>

        <definition firstyear="1950">
            <fixed month="March" day="23"/>
        </definition>

    </holiday>

    <!--
      http://en.wikipedia.org/wiki/Pi_Day
      -->
    <holiday>
        <description language="en" name="Pi Day"/>
        <definition firstyear="1988">
            <fixed month="March" day="14"/>
        </definition>
    </holiday>


    <!-- April -->

    <!--
      http://en.wikipedia.org/wiki/Earth_Day
      -->
    <holiday>
        <description language="en" name="Earth Day"/>
        <definition firstyear="1970">
            <fixed month="April" day="22"/>
        </definition>
    </holiday>


    <!-- May -->

    <holiday>
        <description language="en" name="World Password Day"/>

        <!-- https://www.csoonline.com/article/2919557/microsoft-subnet/world-password-day-2015-change-your-passwords-on-may-7.html
        "May 7[, 2015] is the third annual World Password Day"
        -->
        <definition firstyear="2013">
            <rule nth="First" weekday="Thursday" month="May"/>
        </definition>
    </holiday>

    <!-- 
      http://www.sueddeutsche.de/kultur/artikel/690/115575/
      0x25+0x5=37+5=42 ;)
      -->
    <holiday>
        <description language="en" name="Towel Day"/>
        <definition lastyear="2000">
            <undefined/>
        </definition>
        <definition firstyear="2001">
            <fixed month="May" day="25"/>
        </definition>
    </holiday>

    <!-- June -->
    
    <!-- July -->
    
    <!-- August -->
    
    <!-- September -->
    
    <!-- October -->    

    <!--
      http://en.wikipedia.org/wiki/World_Animal_Day
      -->
    <holiday>
        <description language="en" name="World Animal Day"/>
        <description language="de" name="Welttierschutztag"/>
        <definition firstyear="1931">
            <fixed month="October" day="4"/>
        </definition>
    </holiday>
    
    <!-- November -->
    
    <!-- December -->
    

</holidays>

=== jonelo/xml-holidays/xml/holidays_ddr.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE holidays SYSTEM "holidays.dtd">
<!-- 
    This file is from the free xml-holidays project. See also
    https://github.com/jonelo/xml-holidays/
    Thank you for keeping the comment.
 -->
<holidays country="DDR" valid="false">
    <!-- https://de.wikipedia.org/wiki/Feiertage_in_der_DDR -->
    <!-- Die DDR bestand vom 7. Oktober 1949 bis zum 2. Oktober 1990 -->

    <default language="de"/>

    <holiday>
        <description language="de" name="Neujahr" type="gesetzlich"/>
        <description language="en" name="New Year's Day" type="public holiday"/>

        <definition firstyear="1950" lastyear="1990">
            <fixed month="January" day="1"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Karfreitag" type="gesetzlich"/>
        <description language="en" name="Good Friday" type="public holiday"/>

        <definition firstyear="1950" lastyear="1990">
            <easter/>
            <add days="-2"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Ostersonntag (Ostern)"/>
        <description language="en" name="Easter Sunday"/>

        <definition firstyear="1950" lastyear="1990">
            <easter/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Ostermontag" type="gesetzlich"/>
        <definition firstyear="1950" lastyear="1967">
            <easter/>
            <add days="1"/>
        </definition>
        <definition year="1990">
            <easter/>
            <add days="1"/>
        </definition>

    </holiday>
    
    <holiday>
        <description language="de" name="Internationaler Kampf- und Feiertag der Werktätigen für Frieden und Sozialismus" type="gesetzlich"/>
        <definition firstyear="1950" lastyear="1990">
            <fixed month="May" day="1" />
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Tag der Befreiung" type="gesetzlich"/>
        <definition firstyear="1950" lastyear="1967">
            <fixed month="May" day="8" />
        </definition>
        <definition year="1985">
            <fixed month="May" day="8" />
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Tag des Sieges" type="gesetzlich"/>
        <definition year="1975">
            <fixed month="May" day="9" />
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Christi Himmelfahrt" type="gesetzlich"/>
        <definition firstyear="1950" lastyear="1967">
            <easter/>
            <add days="+39"/>
        </definition>
        <definition year="1990">
            <easter/>
            <add days="+39"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Pfingstsonntag (Pfingsten)" type="gesetzlich"/>
        <definition firstyear="1950" lastyear="1990">
            <easter/>
            <add days="+49"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Pfingstmontag" type="gesetzlich"/>
        <definition firstyear="1950" lastyear="1990">
            <easter/>
            <add days="+50"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Tag der Republik" type="gesetzlich"/>
        <definition firstyear="1949" lastyear="1989">
            <fixed month="October" day="7"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Reformationstag" type="gesetzlich (ausser in den Bezirken Halle, Magdeburg und Berlin (Ost))"/>
        <definition firstyear="1950" lastyear="1966">
            <fixed month="October" day="31"/>
        </definition>
        <definition year="1990">
            <fixed month="October" day="31"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="Buß- und Bettag" type="gesetzlich"/>
        <description language="en" name="Day of Repentance and Prayer" type="public holiday"/>

        <definition firstyear="1950" lastyear="1966">
            <advent/>
            <add days="-11"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="1. Weihnachtsfeiertag (Weihnachten)" type="gesetzlich"/>
        <description language="en" name="Christmas Day" type="public holiday"/>

        <definition firstyear="1949" lastyear="1989">
            <fixed month="December" day="25"/>
        </definition>
    </holiday>
    
    <holiday>
        <description language="de" name="2. Weihnachtsfeiertag (Weihnachten)" type="gesetzlich"/>
        <description language="en" name="Boxing Day" type="public holiday"/>

        <definition firstyear="1949" lastyear="1989">
            <fixed month="December" day="26"/>
        </definition>
    </holiday>
    
</holidays>
